// The OpenNext worker is generated by `opennextjs-cloudflare build`.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore Generated module is intentionally absent before the Cloudflare build but present on repeat builds.
import openNextWorker from './.open-next/worker.js';
import {
  handlePublicExperienceMediaQueueBatch,
  type PublicExperienceMediaQueueBatchLike,
} from './app/utils/publicExperienceMediaQueueConsumer';
import type { PublicExperienceMediaQueueRuntimeEnv } from './app/utils/publicExperienceMediaQueueRuntime';
import { handleExperienceTranslationQueueBatch, type ExperienceTranslationQueueBatchLike, type ExperienceTranslationQueueRuntimeEnv } from './app/utils/experienceTranslation/queueConsumer';
import { EXPERIENCE_TRANSLATION_QUEUE_NAME } from './app/utils/experienceTranslation/queueMessage';
import { EXPERIENCE_TRANSLATION_RECOVERY_CRON, handleExperienceTranslationScheduledRecovery } from './app/utils/experienceTranslation/scheduledRecovery';
import { handleLocallyScheduledEvent } from './app/utils/cloudflareScheduled';
import {
  handleHomePopularitySnapshotScheduled,
  type HomePopularitySnapshotRuntimeEnv,
} from './app/utils/homePopularitySnapshot';
import { PUBLIC_EXPERIENCE_MEDIA_PRODUCTION_QUEUE } from './app/utils/publicExperienceMediaQueueConsumer';
import {
  ADMIN_SUPPORT_UNREAD_ALERTS_CRON,
  handleAdminSupportUnreadAlertsScheduled,
  type AdminSupportUnreadAlertsRuntimeEnv,
} from './app/utils/adminSupportUnreadAlertsScheduled';
import {
  handleNotificationRetentionCleanupScheduled,
  NOTIFICATION_RETENTION_CLEANUP_CRON,
  type NotificationRetentionRuntimeEnv,
} from './app/utils/notificationRetentionCleanup';
import {
  EXPERIENCE_COMPLETION_SYNC_CRON,
  handleExperienceCompletionScheduled,
  type ExperienceCompletionScheduledRuntimeEnv,
} from './app/utils/experienceCompletionScheduled';
import {
  handleServiceCompletionScheduled,
  type ServiceCompletionScheduledRuntimeEnv,
} from './app/utils/serviceCompletionScheduled';

type WorkerEnvironment = PublicExperienceMediaQueueRuntimeEnv & ExperienceTranslationQueueRuntimeEnv & HomePopularitySnapshotRuntimeEnv & AdminSupportUnreadAlertsRuntimeEnv & NotificationRetentionRuntimeEnv & ExperienceCompletionScheduledRuntimeEnv & ServiceCompletionScheduledRuntimeEnv;

const worker = {
  fetch(request: Request, env: WorkerEnvironment, ctx: unknown) {
    return openNextWorker.fetch(request, env, ctx);
  },
  queue(
    batch: PublicExperienceMediaQueueBatchLike | ExperienceTranslationQueueBatchLike,
    env: WorkerEnvironment,
    ctx: unknown
  ) {
    void ctx;
    if (batch.queue === PUBLIC_EXPERIENCE_MEDIA_PRODUCTION_QUEUE) return handlePublicExperienceMediaQueueBatch(batch, env);
    if (batch.queue === EXPERIENCE_TRANSLATION_QUEUE_NAME) return handleExperienceTranslationQueueBatch(batch, env);
    throw new Error('locally_unexpected_queue');
  },
  scheduled(controller: { cron: string }, env: WorkerEnvironment, ctx: unknown) {
    const scheduled = (openNextWorker as unknown as { scheduled?: (controller: { cron: string }, env: WorkerEnvironment, ctx: unknown) => unknown }).scheduled;
    return handleLocallyScheduledEvent(controller, env, {
      dailyCron: EXPERIENCE_TRANSLATION_RECOVERY_CRON,
      adminSupportCron: ADMIN_SUPPORT_UNREAD_ALERTS_CRON,
      notificationRetentionCron: NOTIFICATION_RETENTION_CLEANUP_CRON,
      experienceCompletionCron: EXPERIENCE_COMPLETION_SYNC_CRON,
      runTranslationRecovery: handleExperienceTranslationScheduledRecovery,
      runHomePopularitySnapshot: handleHomePopularitySnapshotScheduled,
      runAdminSupportUnreadAlerts: handleAdminSupportUnreadAlertsScheduled,
      runNotificationRetentionCleanup: handleNotificationRetentionCleanupScheduled,
      runExperienceCompletionSync: handleExperienceCompletionScheduled,
      runServiceCompletionSync: handleServiceCompletionScheduled,
      delegate: typeof scheduled === 'function'
        ? (nextController, nextEnv) => scheduled.call(openNextWorker, nextController, nextEnv, ctx)
        : undefined,
    });
  },
};

export default worker;

// These exports are required by the explicitly bound OpenNext cache Durable Objects.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore Generated module is intentionally absent before the Cloudflare build but present on repeat builds.
export { DOQueueHandler, DOShardedTagCache } from './.open-next/worker.js';
