// The OpenNext worker is generated by `opennextjs-cloudflare build`.
// @ts-expect-error Generated module is intentionally absent before the Cloudflare build.
import openNextWorker from './.open-next/worker.js';
import {
  handlePublicExperienceMediaQueueBatch,
  type PublicExperienceMediaQueueBatchLike,
} from './app/utils/publicExperienceMediaQueueConsumer';
import type { PublicExperienceMediaQueueRuntimeEnv } from './app/utils/publicExperienceMediaQueueRuntime';

const worker = {
  fetch(request: Request, env: PublicExperienceMediaQueueRuntimeEnv, ctx: unknown) {
    return openNextWorker.fetch(request, env, ctx);
  },
  queue(
    batch: PublicExperienceMediaQueueBatchLike,
    env: PublicExperienceMediaQueueRuntimeEnv,
    ctx: unknown
  ) {
    void ctx;
    return handlePublicExperienceMediaQueueBatch(batch, env);
  },
};

export default worker;

// These exports are required by the explicitly bound OpenNext cache Durable Objects.
// @ts-expect-error Generated module is intentionally absent before the Cloudflare build.
export { DOQueueHandler, DOShardedTagCache } from './.open-next/worker.js';
