// The OpenNext worker is generated by `opennextjs-cloudflare build`.
// @ts-expect-error Generated module is intentionally absent before the Cloudflare build.
import openNextWorker from './.open-next/worker.js';

export default openNextWorker;

// These exports are required by the explicitly bound OpenNext cache Durable Objects.
// @ts-expect-error Generated module is intentionally absent before the Cloudflare build.
export { DOQueueHandler, DOShardedTagCache } from './.open-next/worker.js';
