export type QaActor =
  | 'public'
  | 'guest'
  | 'host'
  | 'admin'
  | 'operator'
  | 'support'
  | 'system';

export type QaLocale = 'ko' | 'en' | 'ja' | 'zh';
export type QaViewport = 'desktop' | 'mobile' | 'tablet';
export type QaTier = 'A' | 'B' | 'C';

export type DomainMatrixEntry = {
  id: number;
  slug: string;
  name: string;
  summary: string;
  priority: number;
  tiers: QaTier[];
  actors: QaActor[];
  locales: QaLocale[];
  viewports: QaViewport[];
  canonicalRoutes: string[];
  specs: string[];
  manualChecks: string[];
  blockerCriteria: string[];
  signoffRules: {
    green: string[];
    yellow: string[];
    red: string[];
  };
};

export type ExternalQaBundle = {
  id: string;
  name: string;
  command: string;
  domains: number[];
  description: string;
};

const PUBLIC_LOCALES: QaLocale[] = ['ko', 'en', 'ja', 'zh'];
const INTERNAL_LOCALES: QaLocale[] = ['ko'];
const RESPONSIVE_VIEWPORTS: QaViewport[] = ['desktop', 'mobile', 'tablet'];

const COMMON_PUBLIC_MANUAL_CHECKS = [
  'Copy matches the current actor, state, and CTA outcome.',
  'Non-Korean locales do not leak Korean hard-coded strings.',
  'Primary CTA is visible and clickable on desktop and mobile.',
  'Inputs, buttons, and cards are not too small or too large.',
  'Sticky UI, footer, or modal does not cover primary content.',
  'Mobile viewport has no clipping, overlap, or scroll trap.',
  'Success, error, and empty states read naturally for the page.',
];

const COMMON_INTERNAL_MANUAL_CHECKS = [
  'Admin or host labels match the actual operation being performed.',
  'Primary action buttons are clickable and not hidden by sticky chrome.',
  'Table, tab, and modal layouts remain usable on mobile or tablet.',
  'Critical states and warnings are not visually buried or truncated.',
  'Korean default copy is coherent and fallback copy is not broken.',
];

const STANDARD_SIGNOFF_RULES = {
  green: [
    'Required automated checks pass.',
    'Required manual checklist items are marked pass.',
    'No blocker-grade issue remains open.',
  ],
  yellow: [
    'Core flow is working.',
    'Copy, translation, mobile polish, or visual cleanup remains.',
    'Remaining issues are not release blockers.',
  ],
  red: [
    'Core flow fails or cannot be executed reliably.',
    'A money, permission, data, or global runtime issue remains.',
    'Release should be blocked until the issue is resolved.',
  ],
};

export const DOMAIN_PRIORITY_ORDER = [
  12, 1, 2, 4, 11, 13, 5, 7, 8, 9, 10, 17, 18, 3, 6, 16, 14, 15, 19,
] as const;

export const DOMAIN_QA_BUNDLES = [
  {
    id: 'critical-priority',
    name: 'Critical priority domains',
    domains: [12, 1, 2, 4, 11, 13, 5, 7, 8, 9, 10, 17, 18],
    description: 'Money, auth, runtime, admin core, messaging, and operational gates.',
  },
  {
    id: 'public-surface',
    name: 'Public surface domains',
    domains: [3, 6, 14, 15, 16],
    description: 'Public ingress, trust, content, SEO, and reputation surfaces.',
  },
  {
    id: 'all-domains',
    name: 'All 19 domains',
    domains: [...DOMAIN_PRIORITY_ORDER],
    description: 'Full domain sign-off bundle.',
  },
];

export const EXTERNAL_QA_BUNDLES: ExternalQaBundle[] = [
  {
    id: 'release',
    name: 'Release-only critical journey bundle',
    command: 'npm run test:e2e:journeys:release',
    domains: [4, 5, 6, 10, 12],
    description: 'Cross-domain full journeys for release-day blockers.',
  },
  {
    id: 'contracts',
    name: 'Baseline contract bundle',
    command: 'npm run test:e2e:contracts',
    domains: [1, 2, 4, 5, 6, 11, 17, 18],
    description: 'Fail-closed route, callback, guard, and notification contract checks.',
  },
  {
    id: 'live-gate',
    name: 'Live gate smoke bundle',
    command: 'npm run test:e2e:live:gate',
    domains: [3, 6, 11, 16, 17, 18],
    description: 'Production-safe live smoke bundle for shared deploy gates.',
  },
];

export const MANUAL_RESULT_SCHEMA = {
  version: 1,
  shape: {
    generatedAt: 'ISO-8601 timestamp',
    domains: {
      '<domain-id>': {
        status: 'pass | fail | pending | n/a',
        notes: ['free-form note'],
        artifacts: ['relative or absolute path'],
        checks: [
          {
            route: 'checked route',
            actor: 'public | guest | host | admin | operator | support | system',
            locale: 'ko | en | ja | zh',
            viewport: 'desktop | mobile | tablet',
            area: 'copy | translation | ux | ui | a11y | tap-target | overflow | state',
            status: 'pass | fail | pending | n/a',
            note: 'free-form note',
          },
        ],
      },
    },
  },
} as const;

export const DOMAIN_MATRIX: DomainMatrixEntry[] = [
  {
    id: 1,
    slug: 'global-runtime-auth-locale-routing',
    name: 'Global runtime, auth, locale, and routing',
    summary: 'Top-level runtime shell, auth transitions, locale propagation, and routing contracts.',
    priority: 2,
    tiers: ['A', 'B', 'C'],
    actors: ['public', 'guest', 'host', 'admin'],
    locales: PUBLIC_LOCALES,
    viewports: RESPONSIVE_VIEWPORTS,
    canonicalRoutes: ['/', '/login', '/signup', '/auth/callback', '/guest/trips'],
    specs: [
      'tests/e2e/73-kakao-iab-gate.spec.ts',
      'tests/e2e/108-login-flow-guidance.spec.ts',
      'tests/e2e/128-auth-success-transition.spec.ts',
      'tests/e2e/165-guest-wishlist-account-continuity.spec.ts',
      'tests/e2e/169-account-accessibility-auth-surfaces.spec.ts',
      'tests/e2e/177-site-url-runtime-contract.spec.ts',
      'tests/e2e/178-configured-site-url-helper-contract.spec.ts',
      'tests/e2e/183-auth-runtime-contract.spec.ts',
    ],
    manualChecks: [
      ...COMMON_PUBLIC_MANUAL_CHECKS,
      'Locale cookie, header, and page copy stay aligned after login or redirect.',
      'Guest, host, and admin redirects do not bounce to the wrong home surface.',
    ],
    blockerCriteria: [
      'Login or signup cannot complete.',
      'Locale changes desync the shell and routed page content.',
      'Critical redirects or auth guards route actors to the wrong surface.',
    ],
    signoffRules: STANDARD_SIGNOFF_RULES,
  },
  {
    id: 2,
    slug: 'data-layer-supabase-rls-rpc-storage',
    name: 'Data layer, Supabase, RLS, RPC, and storage',
    summary: 'Shared DB contract, RLS boundaries, public write safety, and storage guardrails.',
    priority: 3,
    tiers: ['A'],
    actors: ['public', 'guest', 'host', 'admin', 'system'],
    locales: INTERNAL_LOCALES,
    viewports: ['desktop'],
    canonicalRoutes: ['/api/bookings', '/api/services', '/api/proxy-bookings', '/api/admin/access'],
    specs: [
      'tests/e2e/68-booking-rpc-public-guard.spec.ts',
      'tests/e2e/80-public-service-role-contract.spec.ts',
      'tests/e2e/139-storage-upload-diagnostic-util.spec.ts',
    ],
    manualChecks: [
      'Manual review confirms no unexpected public write path or broad data exposure.',
      'Protected APIs fail closed when auth or owner context is missing.',
      'Upload or storage paths do not leak public assets unintentionally.',
    ],
    blockerCriteria: [
      'Public or low-privilege actor can bypass RLS or protected write boundaries.',
      'Critical storage path or RPC contract leaks cross-user data.',
    ],
    signoffRules: STANDARD_SIGNOFF_RULES,
  },
  {
    id: 3,
    slug: 'home-search-public-discovery',
    name: 'Home, search, and public discovery',
    summary: 'Public ingress, search behavior, filter labels, and responsive discovery UX.',
    priority: 14,
    tiers: ['B', 'C'],
    actors: ['public', 'guest'],
    locales: PUBLIC_LOCALES,
    viewports: RESPONSIVE_VIEWPORTS,
    canonicalRoutes: ['/', '/search', '/search?city=seoul', '/experiences/[id]'],
    specs: [
      'tests/e2e/43-guest-search-detail-ingress.spec.ts',
      'tests/e2e/58-search-server-filters.spec.ts',
      'tests/e2e/107-home-landing-ingress.spec.ts',
      'tests/e2e/111-search-map-panel.spec.ts',
      'tests/e2e/114-search-mobile-city-filter.spec.ts',
      'tests/e2e/137-home-search-location-localization.spec.ts',
      'tests/e2e/138-search-location-label-util.spec.ts',
      'tests/e2e/142-home-mobile-city-shortcuts.spec.ts',
      'tests/e2e/143-search-mobile-header-city-picker.spec.ts',
      'tests/e2e/144-home-experience-sections.spec.ts',
      'tests/e2e/145-home-load-error-state.spec.ts',
      'tests/e2e/146-home-popularity-snapshot-fail-open.spec.ts',
      'tests/e2e/147-home-search-card-meta-parity.spec.ts',
      'tests/e2e/183-search-text-util.spec.ts',
      'tests/e2e/184-search-route-contract.spec.ts',
    ],
    manualChecks: [
      ...COMMON_PUBLIC_MANUAL_CHECKS,
      'Search filter labels, city chips, and mobile header controls feel native on narrow screens.',
      'Cards, badges, and map or filter panels do not overflow or stack awkwardly.',
    ],
    blockerCriteria: [
      'Search results, filters, or ingress path are broken or materially misleading.',
      'Public discovery is unusable on mobile.',
      'Major copy or translation mismatch makes search intent unclear.',
    ],
    signoffRules: STANDARD_SIGNOFF_RULES,
  },
  {
    id: 4,
    slug: 'experience-booking-payment-trips',
    name: 'Experience detail, booking, payment, and guest trips',
    summary: 'Primary revenue chain from detail to booking, payment confirmation, and trips follow-up.',
    priority: 4,
    tiers: ['A', 'B'],
    actors: ['public', 'guest'],
    locales: PUBLIC_LOCALES,
    viewports: RESPONSIVE_VIEWPORTS,
    canonicalRoutes: [
      '/experiences/[id]',
      '/experiences/[id]/payment',
      '/guest/trips',
      '/payment/success',
    ],
    specs: [
      'tests/e2e/01-fully-integrated-ecosystem.spec.ts',
      'tests/e2e/02-experience-booking.spec.ts',
      'tests/e2e/24-experience-card-verification.spec.ts',
      'tests/e2e/31-live-guest-trip-cancel.spec.ts',
      'tests/e2e/42-experience-paypal-payment.spec.ts',
      'tests/e2e/44-experience-card-payment-ui.spec.ts',
      'tests/e2e/52-guest-trip-metadata.spec.ts',
      'tests/e2e/57-guest-trips-sync-completed.spec.ts',
      'tests/e2e/64-experience-availability-detail.spec.ts',
      'tests/e2e/65-experience-post-confirm-detail-refresh.spec.ts',
      'tests/e2e/66-bookings-solo-guard.spec.ts',
      'tests/e2e/74-card-payment-precutover-contract.spec.ts',
      'tests/e2e/75-experience-cancel-error-safe.spec.ts',
      'tests/e2e/76-card-callback-contract.spec.ts',
      'tests/e2e/90-booking-cancel-policy.spec.ts',
      'tests/e2e/91-private-tour-guest-count.spec.ts',
      'tests/e2e/94-guest-trips-priority.spec.ts',
      'tests/e2e/124-experience-payment-feedback.spec.ts',
      'tests/e2e/125-experience-bank-payment-success.spec.ts',
      'tests/e2e/127-experience-payment-state-system.spec.ts',
      'tests/e2e/135-experience-bank-confirm-snapshot-parity.spec.ts',
      'tests/e2e/136-experience-payment-conflict-localization.spec.ts',
      'tests/e2e/150-experience-bank-confirm-guard.spec.ts',
      'tests/e2e/165-card-payment-provider-cutover.spec.ts',
      'tests/e2e/166-prebooking-share-guardrails.spec.ts',
      'tests/e2e/181-experience-booking-login-continuity.spec.ts',
      'tests/e2e/186-experience-paypal-payment-lock.spec.ts',
      'tests/e2e/23-live-guest-post-booking.spec.ts',
    ],
    manualChecks: [
      ...COMMON_PUBLIC_MANUAL_CHECKS,
      'Booking card, payment CTA, and pricing breakdown remain legible across viewports.',
      'Success, cancel, and conflict states match the actual booking state machine.',
      'Trips list and trip detail remain coherent after payment, cancel, or confirm transitions.',
    ],
    blockerCriteria: [
      'Booking cannot be created, confirmed, or safely canceled.',
      'Payment verification or callback contract is broken.',
      'Trips or payment success surfaces show the wrong booking state.',
    ],
    signoffRules: STANDARD_SIGNOFF_RULES,
  },
  {
    id: 5,
    slug: 'messaging-inquiries-support-boundary',
    name: 'Messaging, inquiries, and support boundary',
    summary: 'Guest-host-admin messaging semantics, support thread boundaries, and inbox continuity.',
    priority: 7,
    tiers: ['A', 'B'],
    actors: ['guest', 'host', 'admin', 'support'],
    locales: ['ko', 'en', 'ja', 'zh'],
    viewports: RESPONSIVE_VIEWPORTS,
    canonicalRoutes: ['/guest/inbox', '/host/dashboard', '/admin/dashboard', '/api/inquiries'],
    specs: [
      'tests/e2e/05-live-guest-booking-messaging-support.spec.ts',
      'tests/e2e/40-host-reservations-inquiries-ui.spec.ts',
      'tests/e2e/41-inquiry-read-route.spec.ts',
      'tests/e2e/53-chat-optimistic-send.spec.ts',
      'tests/e2e/60-inquiry-thread-contract.spec.ts',
      'tests/e2e/82-chat-policy-signal-util.spec.ts',
      'tests/e2e/83-chat-policy-monitoring.spec.ts',
      'tests/e2e/95-guest-inbox-empty-state.spec.ts',
      'tests/e2e/164-guest-inbox-support-profile-context.spec.ts',
      'tests/e2e/185-messaging-boundary-contract.spec.ts',
      'tests/e2e/198-host-reservation-timing-contract.spec.ts',
      'tests/e2e/222-global-support-report.spec.ts',
    ],
    manualChecks: [
      ...COMMON_PUBLIC_MANUAL_CHECKS,
      ...COMMON_INTERNAL_MANUAL_CHECKS,
      'Unread markers, thread ownership, and support context are correct for each actor.',
      'Thread navigation remains usable on mobile and narrow inbox layouts.',
    ],
    blockerCriteria: [
      'Wrong actor can read or post to a thread.',
      'Support or inquiry boundary reuses the wrong thread truth.',
      'Inbox or chat UI is unusable on mobile for core flows.',
    ],
    signoffRules: STANDARD_SIGNOFF_RULES,
  },
  {
    id: 6,
    slug: 'reviews-public-host-profile-reputation',
    name: 'Reviews, public host profile, and reputation surfaces',
    summary: 'Review write/reply/public rendering, host profile projection, and moderation touchpoints.',
    priority: 15,
    tiers: ['A', 'B', 'C'],
    actors: ['public', 'guest', 'host', 'admin'],
    locales: PUBLIC_LOCALES,
    viewports: RESPONSIVE_VIEWPORTS,
    canonicalRoutes: ['/users/[id]', '/experiences/[id]', '/api/reviews', '/admin/dashboard'],
    specs: [
      'tests/e2e/39-host-review-routes.spec.ts',
      'tests/e2e/71-public-host-profile.spec.ts',
      'tests/e2e/72-review-host-notification.spec.ts',
      'tests/e2e/92-host-unavailable-review-notifications.spec.ts',
      'tests/e2e/148-experience-detail-review-rendering.spec.ts',
      'tests/e2e/149-review-photo-deprecation.spec.ts',
      'tests/e2e/164-review-route-contract.spec.ts',
      'tests/e2e/193-guest-review-host-reply-public-journey.spec.ts',
      'tests/e2e/194-admin-review-moderation-journey.spec.ts',
    ],
    manualChecks: [
      ...COMMON_PUBLIC_MANUAL_CHECKS,
      'Public host profile and review aggregates do not leak hidden or masked information.',
      'Review cards, reply UI, and moderation affordances remain readable on mobile.',
    ],
    blockerCriteria: [
      'Review permissions or public profile visibility are incorrect.',
      'Public review rendering is broken or misleading.',
      'Moderation path cannot safely change visible review state.',
    ],
    signoffRules: STANDARD_SIGNOFF_RULES,
  },
  {
    id: 7,
    slug: 'host-onboarding-approval-public-transition',
    name: 'Host onboarding, approval, and public transition',
    summary: 'Host registration, revision, approval, landing, and public visibility transition.',
    priority: 8,
    tiers: ['A', 'B', 'C'],
    actors: ['public', 'host', 'admin'],
    locales: PUBLIC_LOCALES,
    viewports: RESPONSIVE_VIEWPORTS,
    canonicalRoutes: ['/become-a-host', '/host/register', '/admin/dashboard', '/host/dashboard'],
    specs: [
      'tests/e2e/03-live-host-signup-registration.spec.ts',
      'tests/e2e/07-admin-approvals.spec.ts',
      'tests/e2e/36-host-register-submit.spec.ts',
      'tests/e2e/97-host-register-visibility.spec.ts',
      'tests/e2e/98-host-approved-welcome-overlay.spec.ts',
      'tests/e2e/109-host-landing-guidance.spec.ts',
      'tests/e2e/126-host-public-visibility.spec.ts',
      'tests/e2e/140-host-status-refresh-after-approval.spec.ts',
      'tests/e2e/141-host-landing-cta-refresh-after-approval.spec.ts',
      'tests/e2e/164-admin-host-approval-happy-path.spec.ts',
      'tests/e2e/167-host-register-revision-resubmit-ui.spec.ts',
      'tests/e2e/186-host-guidelines-popularity-copy.spec.ts',
    ],
    manualChecks: [
      ...COMMON_PUBLIC_MANUAL_CHECKS,
      ...COMMON_INTERNAL_MANUAL_CHECKS,
      'Host landing copy and revision flow explain the current status clearly.',
      'Approval transition makes the dashboard and public visibility state obvious.',
    ],
    blockerCriteria: [
      'Host application cannot be submitted, revised, or approved.',
      'Approved host does not transition to the correct operational state.',
      'Public transition or visibility remains stale after approval.',
    ],
    signoffRules: STANDARD_SIGNOFF_RULES,
  },
  {
    id: 8,
    slug: 'host-dashboard-experience-crud-schedule-earnings',
    name: 'Host dashboard, experience CRUD, schedule, and earnings',
    summary: 'Host operational dashboard, experience management, scheduling, and earnings UX.',
    priority: 9,
    tiers: ['B', 'C'],
    actors: ['host'],
    locales: ['ko', 'en'],
    viewports: RESPONSIVE_VIEWPORTS,
    canonicalRoutes: [
      '/host/dashboard',
      '/host/create',
      '/host/experiences/[id]',
      '/host/earnings',
      '/api/host/reservations/guest-memberships',
    ],
    specs: [
      'tests/e2e/04-live-host-experience-create.spec.ts',
      'tests/e2e/32-host-schedule-save.spec.ts',
      'tests/e2e/33-host-experience-delete.spec.ts',
      'tests/e2e/34-host-edit-and-dates-ui.spec.ts',
      'tests/e2e/35-host-experience-detail-delete-ui.spec.ts',
      'tests/e2e/37-host-earnings-policy.spec.ts',
      'tests/e2e/38-host-profile-save.spec.ts',
      'tests/e2e/51-host-mobile-photo-actions.spec.ts',
      'tests/e2e/55-host-view-mode-persistence.spec.ts',
      'tests/e2e/93-host-create-copy-layout.spec.ts',
      'tests/e2e/129-host-profile-language-dedup.spec.ts',
      'tests/e2e/152-host-service-earnings-separation.spec.ts',
      'tests/e2e/153-host-unified-earnings-summary.spec.ts',
      'tests/e2e/154-host-earnings-mobile-layout.spec.ts',
      'tests/e2e/179-host-service-earnings-null-request-guard.spec.ts',
      'tests/e2e/197-host-guest-memberships-contract.spec.ts',
    ],
    manualChecks: [
      ...COMMON_INTERNAL_MANUAL_CHECKS,
      'Dashboard tab structure and information hierarchy remain understandable on tablet and mobile.',
      'Create/edit forms keep primary inputs, validation, and save actions visible on narrow screens.',
    ],
    blockerCriteria: [
      'Host cannot create, update, schedule, or delete an experience reliably.',
      'Earnings summary or dashboard state is materially wrong.',
      'Host dashboard is unusable on mobile or tablet for core operations.',
    ],
    signoffRules: STANDARD_SIGNOFF_RULES,
  },
  {
    id: 9,
    slug: 'service-marketplace-request-match-payment',
    name: 'Service marketplace request, matching, and payment',
    summary: 'Service request creation, host selection, payment, chat, and completion lifecycle.',
    priority: 10,
    tiers: ['A', 'B'],
    actors: ['public', 'guest', 'host', 'admin'],
    locales: PUBLIC_LOCALES,
    viewports: RESPONSIVE_VIEWPORTS,
    canonicalRoutes: ['/services', '/services/new', '/services/[requestId]/payment', '/admin/dashboard'],
    specs: [
      'tests/e2e/10-admin-service-requests.spec.ts',
      'tests/e2e/12-service-paypal-payment.spec.ts',
      'tests/e2e/19-service-card-verification.spec.ts',
      'tests/e2e/20-service-cancel-error-safe.spec.ts',
      'tests/e2e/21-service-payment-method-lock.spec.ts',
      'tests/e2e/48-service-visibility.spec.ts',
      'tests/e2e/49-service-request-contract.spec.ts',
      'tests/e2e/50-service-select-host-atomicity.spec.ts',
      'tests/e2e/102-service-request-form-layout.spec.ts',
      'tests/e2e/106-service-host-flow-guidance.spec.ts',
      'tests/e2e/151-service-bank-confirm-guard.spec.ts',
      'tests/e2e/191-service-bank-open-match-chat-journey.spec.ts',
    ],
    manualChecks: [
      ...COMMON_PUBLIC_MANUAL_CHECKS,
      ...COMMON_INTERNAL_MANUAL_CHECKS,
      'Service request creation, matching, and payment states are understandable to both guest and host.',
      'Request detail, host selection, and payment CTA remain usable on mobile.',
    ],
    blockerCriteria: [
      'Service request cannot be created, matched, or paid safely.',
      'Host selection atomicity or payment method lock is broken.',
      'Service request state transitions drift from the UI or admin truth.',
    ],
    signoffRules: STANDARD_SIGNOFF_RULES,
  },
  {
    id: 10,
    slug: 'proxy-booking-linked-inquiry-bridge',
    name: 'Proxy booking, phone reservation, and linked inquiry bridge',
    summary: 'Proxy request self-service, admin action, and linked inquiry bridge behavior.',
    priority: 11,
    tiers: ['A', 'B', 'C'],
    actors: ['guest', 'admin', 'operator'],
    locales: PUBLIC_LOCALES,
    viewports: RESPONSIVE_VIEWPORTS,
    canonicalRoutes: ['/proxy-bookings/new', '/guest/inbox', '/admin/dashboard', '/api/proxy-bookings'],
    specs: [
      'tests/e2e/86-proxy-booking-team-workspace.spec.ts',
      'tests/e2e/87-proxy-booking-fee-util.spec.ts',
      'tests/e2e/88-proxy-booking-mobile-layout.spec.ts',
      'tests/e2e/105-proxy-booking-self-service.spec.ts',
      'tests/e2e/192-proxy-self-service-admin-refund-linked-inquiry-journey.spec.ts',
    ],
    manualChecks: [
      ...COMMON_PUBLIC_MANUAL_CHECKS,
      ...COMMON_INTERNAL_MANUAL_CHECKS,
      'Self-service and admin views agree on linked inquiry and payment state.',
      'Proxy mobile form layout and payment explanations remain legible on narrow devices.',
    ],
    blockerCriteria: [
      'Linked inquiry bridge breaks between guest and admin surfaces.',
      'Proxy payment or refund state drifts between self-service and admin truth.',
      'Proxy request flow is unusable on mobile.',
    ],
    signoffRules: STANDARD_SIGNOFF_RULES,
  },
  {
    id: 11,
    slug: 'admin-core-access-sidebar-approvals-users-alerts-chats-reviews',
    name: 'Admin core access, sidebar, users, alerts, chats, and review operations',
    summary: 'Admin access boundary and the active dashboard surfaces used for monitoring and moderation.',
    priority: 5,
    tiers: ['A', 'B', 'C'],
    actors: ['admin', 'operator', 'support'],
    locales: INTERNAL_LOCALES,
    viewports: RESPONSIVE_VIEWPORTS,
    canonicalRoutes: ['/admin/dashboard', '/admin/dashboard?tab=USERS', '/admin/dashboard?tab=ALERTS'],
    specs: [
      'tests/e2e/11-admin-users.spec.ts',
      'tests/e2e/13-admin-alerts.spec.ts',
      'tests/e2e/14-admin-chats.spec.ts',
      'tests/e2e/17-admin-sidebar.spec.ts',
      'tests/e2e/69-admin-role-access.spec.ts',
      'tests/e2e/70-admin-audit-logs.spec.ts',
      'tests/e2e/161-admin-support-unread-alerts.spec.ts',
    ],
    manualChecks: [
      ...COMMON_INTERNAL_MANUAL_CHECKS,
      'Sidebar labels, counts, and tabs match the active admin surface.',
      'User, alert, chat, and moderation actions are visible without layout breakage.',
    ],
    blockerCriteria: [
      'Admin access leaks or legitimate admins are locked out.',
      'Core admin monitoring tabs cannot be used.',
      'Critical alert, chat, or user timeline data is missing or stale.',
    ],
    signoffRules: STANDARD_SIGNOFF_RULES,
  },
  {
    id: 12,
    slug: 'admin-finance-ledger-payout-settlement-sync',
    name: 'Admin finance, ledger, payout, and settlement sync',
    summary: 'Financial correctness, manual triggers, payout guardrails, and settlement synchronization.',
    priority: 1,
    tiers: ['A'],
    actors: ['admin', 'operator', 'system'],
    locales: INTERNAL_LOCALES,
    viewports: ['desktop', 'tablet'],
    canonicalRoutes: [
      '/admin/dashboard?tab=SALES',
      '/admin/dashboard?tab=LEDGER',
      '/admin/dashboard?tab=SETTLEMENT',
    ],
    specs: [
      'tests/e2e/06-admin-master-ledger.spec.ts',
      'tests/e2e/08-admin-billing.spec.ts',
      'tests/e2e/115-admin-master-ledger-confirm-modal.spec.ts',
      'tests/e2e/130-admin-settle-host-payout-guard.spec.ts',
      'tests/e2e/131-service-completion-cron.spec.ts',
      'tests/e2e/132-service-payout-eligibility-after-completion.spec.ts',
      'tests/e2e/133-host-payout-summary-reflection.spec.ts',
      'tests/e2e/134-admin-payout-queue-unified-host-rollup.spec.ts',
      'tests/e2e/142-booking-finance-fallback.spec.ts',
      'tests/e2e/155-admin-settlement-sync-status.spec.ts',
      'tests/e2e/156-admin-settlement-sync-manual-trigger.spec.ts',
      'tests/e2e/157-settlement-sync-race-guard.spec.ts',
      'tests/e2e/158-settlement-sync-fail-closed.spec.ts',
      'tests/e2e/159-experience-completion-kst-boundary.spec.ts',
      'tests/e2e/160-settlement-sync-job-name-recording.spec.ts',
      'tests/e2e/195-admin-finance-operator-saga.spec.ts',
    ],
    manualChecks: [
      ...COMMON_INTERNAL_MANUAL_CHECKS,
      'Amounts, payout statuses, and settlement health panels remain visually trustworthy.',
      'Manual trigger and confirm/refund actions require deliberate operator intent.',
    ],
    blockerCriteria: [
      'Money state, payout queue, or settlement sync is wrong or fail-open.',
      'Admin trigger can duplicate or race financial side effects.',
      'Operator cannot see or act on settlement backlog health.',
    ],
    signoffRules: STANDARD_SIGNOFF_RULES,
  },
  {
    id: 13,
    slug: 'admin-team-workspace-internal-tools-load-hotspot',
    name: 'Admin team workspace, internal tools, and load hotspots',
    summary: 'Internal team workspace, analytics fan-out, badge state, and admin-heavy load surfaces.',
    priority: 6,
    tiers: ['A', 'B', 'C'],
    actors: ['admin', 'operator', 'support'],
    locales: INTERNAL_LOCALES,
    viewports: RESPONSIVE_VIEWPORTS,
    canonicalRoutes: ['/admin/dashboard?tab=TEAM', '/admin/dashboard?tab=ANALYTICS'],
    specs: [
      'tests/e2e/09-admin-analytics.spec.ts',
      'tests/e2e/15-admin-team.spec.ts',
      'tests/e2e/16-admin-team-chat.spec.ts',
      'tests/e2e/18-admin-team-badge.spec.ts',
      'tests/e2e/45-team-notify-policy.spec.ts',
      'tests/e2e/79-team-notify-guard.spec.ts',
      'tests/e2e/89-admin-team-mobile.spec.ts',
      'tests/e2e/136-team-workspace-retention.spec.ts',
      'tests/e2e/196-admin-team-memo-comment-scroll.spec.ts',
      'tests/e2e/197-admin-team-refresh.spec.ts',
    ],
    manualChecks: [
      ...COMMON_INTERNAL_MANUAL_CHECKS,
      'Heavy admin tabs do not trigger obvious duplicate refresh or confusing count behavior.',
      'Team workspace memo, comment, chat, and badge surfaces remain usable on tablet and mobile.',
    ],
    blockerCriteria: [
      'Internal team workspace breaks core operator coordination.',
      'Admin hotspot surfaces become unusable due to obvious refresh or state drift.',
      'Key analytics or badge states are misleading enough to block operations.',
    ],
    signoffRules: STANDARD_SIGNOFF_RULES,
  },
  {
    id: 14,
    slug: 'community-locally-content-publication',
    name: 'Community and Locally content publication',
    summary: 'Public editorial content, feed behavior, author surfaces, and moderation-safe rendering.',
    priority: 17,
    tiers: ['B', 'C'],
    actors: ['public', 'guest', 'admin'],
    locales: PUBLIC_LOCALES,
    viewports: RESPONSIVE_VIEWPORTS,
    canonicalRoutes: ['/community', '/community/[id]'],
    specs: [
      'tests/e2e/46-community-detail-state.spec.ts',
      'tests/e2e/47-community-post-route.spec.ts',
      'tests/e2e/59-community-feed-contract.spec.ts',
      'tests/e2e/61-community-view-count.spec.ts',
      'tests/e2e/62-community-author-modal.spec.ts',
      'tests/e2e/63-community-content-layout.spec.ts',
      'tests/e2e/190-community-paused-runtime-contract.spec.ts',
    ],
    manualChecks: [
      ...COMMON_PUBLIC_MANUAL_CHECKS,
      'Editorial layout, author metadata, and category labels remain polished on mobile.',
      'Public content states, pause banners, and moderation edges are understandable.',
    ],
    blockerCriteria: [
      'Community feed or detail rendering is broken.',
      'Public write or read state drifts from moderation intent.',
    ],
    signoffRules: STANDARD_SIGNOFF_RULES,
  },
  {
    id: 15,
    slug: 'company-brand-help-legal-sitemap',
    name: 'Company, brand, help, legal, and trust surfaces',
    summary: 'Public trust and brand surfaces, help pages, company notices, and static utility pages.',
    priority: 18,
    tiers: ['B', 'C'],
    actors: ['public'],
    locales: PUBLIC_LOCALES,
    viewports: RESPONSIVE_VIEWPORTS,
    canonicalRoutes: ['/about', '/company', '/help', '/site-map'],
    specs: [
      'tests/e2e/103-site-announcements.spec.ts',
      'tests/e2e/104-help-self-service.spec.ts',
      'tests/e2e/110-partnership-media-kit.spec.ts',
      'tests/e2e/113-membership-care.spec.ts',
      'tests/e2e/172-partnership-inquiry-route.spec.ts',
      'tests/e2e/173-public-company-surface-cta.spec.ts',
      'tests/e2e/174-public-company-mobile-back.spec.ts',
      'tests/e2e/175-public-company-notices.spec.ts',
      'tests/e2e/180-footer-test-hidden.spec.ts',
      'tests/e2e/196-about-image-landing-locale-gate.spec.ts',
    ],
    manualChecks: [
      ...COMMON_PUBLIC_MANUAL_CHECKS,
      'Brand, legal, and help surfaces read like intentional public trust pages rather than placeholders.',
      'Back navigation, footer links, and notices remain usable on mobile.',
    ],
    blockerCriteria: [
      'Critical public trust or help page is broken or misleading.',
      'Mobile navigation or layout makes trust content unreadable.',
    ],
    signoffRules: STANDARD_SIGNOFF_RULES,
  },
  {
    id: 16,
    slug: 'seo-metadata-domain-analytics-adsense',
    name: 'SEO, metadata, domain, analytics, and Adsense',
    summary: 'Canonical metadata, sitemap and robots, analytics ingestion, domain parity, and ad gates.',
    priority: 16,
    tiers: ['A', 'B', 'C'],
    actors: ['public', 'system', 'admin'],
    locales: PUBLIC_LOCALES,
    viewports: ['desktop', 'mobile'],
    canonicalRoutes: ['/', '/robots.txt', '/sitemap.xml', '/api/analytics'],
    specs: [
      'tests/e2e/25-public-metadata.spec.ts',
      'tests/e2e/26-private-noindex.spec.ts',
      'tests/e2e/27-dynamic-detail-seo.spec.ts',
      'tests/e2e/28-json-ld.spec.ts',
      'tests/e2e/29-sitemap.spec.ts',
      'tests/e2e/30-robots-policy.spec.ts',
      'tests/e2e/67-analytics-ingest-routes.spec.ts',
      'tests/e2e/170-adsense-contract.spec.ts',
      'tests/e2e/188-vercel-analytics-runtime-contract.spec.ts',
      'tests/e2e/213-google-analytics-contract.spec.ts',
    ],
    manualChecks: [
      ...COMMON_PUBLIC_MANUAL_CHECKS,
      'Canonical, hreflang, and metadata do not visibly contradict the current locale or domain.',
      'Public ad or analytics surfaces do not intrude on basic page usability.',
    ],
    blockerCriteria: [
      'Metadata, analytics, or public domain behavior is materially wrong.',
      'Adsense or analytics configuration blocks normal page use or deploy parity.',
    ],
    signoffRules: STANDARD_SIGNOFF_RULES,
  },
  {
    id: 17,
    slug: 'email-notification-delivery-pipeline',
    name: 'Email, notification, and delivery pipeline',
    summary: 'Transactional email copy, notification creation boundaries, and localized delivery surfaces.',
    priority: 12,
    tiers: ['A', 'B', 'C'],
    actors: ['guest', 'host', 'admin', 'system'],
    locales: PUBLIC_LOCALES,
    viewports: RESPONSIVE_VIEWPORTS,
    canonicalRoutes: ['/guest/inbox', '/host/dashboard', '/admin/dashboard', '/api/notifications'],
    specs: [
      'tests/e2e/22-service-host-notification-scope.spec.ts',
      'tests/e2e/54-mobile-notification-badges.spec.ts',
      'tests/e2e/56-notification-read-route.spec.ts',
      'tests/e2e/77-notification-email-policy.spec.ts',
      'tests/e2e/110-guest-notifications-guidance.spec.ts',
      'tests/e2e/116-notification-copy-util.spec.ts',
      'tests/e2e/117-notification-localization-runtime.spec.ts',
      'tests/e2e/118-service-notification-localization.spec.ts',
      'tests/e2e/119-proxy-notification-localization.spec.ts',
      'tests/e2e/120-email-copy-util.spec.ts',
      'tests/e2e/121-booking-template-email-copy.spec.ts',
      'tests/e2e/122-review-reply-notification-localization.spec.ts',
      'tests/e2e/123-cancellation-approved-notification-localization.spec.ts',
      'tests/e2e/124-inquiry-email-localization.spec.ts',
      'tests/e2e/125-shared-notification-email-cta.spec.ts',
      'tests/e2e/162-email-template-render-contract.spec.ts',
      'tests/e2e/163-email-template-mobile-design.spec.ts',
      'tests/e2e/168-admin-email-sender-contract.spec.ts',
      'tests/e2e/176-inquiry-email-provider-contract.spec.ts',
      'tests/e2e/177-notification-delivery-boundaries.spec.ts',
    ],
    manualChecks: [
      ...COMMON_PUBLIC_MANUAL_CHECKS,
      ...COMMON_INTERNAL_MANUAL_CHECKS,
      'Localized notification and email copy matches the actual event and recipient role.',
      'Badges, notification trays, and template previews stay readable on mobile.',
    ],
    blockerCriteria: [
      'Notification or email goes to the wrong actor or wrong locale.',
      'Delivery boundary allows unauthorized or duplicate sends.',
      'Critical notification UI is unusable on mobile.',
    ],
    signoffRules: STANDARD_SIGNOFF_RULES,
  },
  {
    id: 18,
    slug: 'cron-jobs-ops-scripts-playwright-gate-runbook',
    name: 'Cron, jobs, ops scripts, Playwright gate, and runbook',
    summary: 'Operational scripts, live gate contracts, cron authentication, and release automation safety.',
    priority: 13,
    tiers: ['A', 'B'],
    actors: ['system', 'admin', 'operator'],
    locales: INTERNAL_LOCALES,
    viewports: ['desktop'],
    canonicalRoutes: ['/api/cron/*', '/api/health', '/admin/dashboard'],
    specs: [
      'tests/e2e/81-cron-secret-guards.spec.ts',
      'tests/e2e/171-live-base-url-contract.spec.ts',
      'tests/e2e/189-live-domain-parity-contract.spec.ts',
      'tests/e2e/221-scheduled-cron-workflow-contract.spec.ts',
    ],
    manualChecks: [
      'Runbook, smoke scripts, and cron auth inputs match the live environment contract.',
      'Operational commands clearly indicate whether they are local, preview, or live safe.',
    ],
    blockerCriteria: [
      'Cron auth or operational gate fails open.',
      'Live or preview gate scripts target the wrong domain or environment.',
    ],
    signoffRules: STANDARD_SIGNOFF_RULES,
  },
  {
    id: 19,
    slug: 'legacy-dead-code-dormant-compatibility',
    name: 'Legacy, dead code, and dormant compatibility surfaces',
    summary: 'Legacy success routes, alias redirects, dormant compatibility seams, and cleanup candidates.',
    priority: 19,
    tiers: ['B', 'C'],
    actors: ['public', 'host', 'admin'],
    locales: PUBLIC_LOCALES,
    viewports: RESPONSIVE_VIEWPORTS,
    canonicalRoutes: ['/payment/success', '/become-a-host2', '/admin/dashboard'],
    specs: [
      'tests/e2e/181-payment-success-legacy-gate.spec.ts',
      'tests/e2e/182-become-a-host2-alias-redirect.spec.ts',
      'tests/e2e/187-host-register-admin-alert-compat.spec.ts',
    ],
    manualChecks: [
      'Legacy alias and compatibility routes make the current behavior explicit instead of silently drifting.',
      'Dormant surfaces do not expose stale or broken public UI.',
    ],
    blockerCriteria: [
      'Legacy route exposes the wrong state or public surface.',
      'Dormant compatibility path still mutates active data unexpectedly.',
    ],
    signoffRules: STANDARD_SIGNOFF_RULES,
  },
];
