import { readFileSync } from 'node:fs';
import { PGlite } from '@electric-sql/pglite';

export const migration = readFileSync('supabase/migrations/20261001170718_admin_message_monitoring_phase_1.sql', 'utf8');
export const guest = '11111111-1111-4111-8111-111111111111';
export const host = '22222222-2222-4222-8222-222222222222';
export const admin = '33333333-3333-4333-8333-333333333333';
export const whitelist = '44444444-4444-4444-8444-444444444444';
export const outsider = '55555555-5555-4555-8555-555555555555';

export async function fixture() {
  const db = new PGlite();
  await db.exec(`
    CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role BYPASSRLS;
    CREATE SCHEMA auth; CREATE SCHEMA private;
    CREATE TABLE auth.users (id uuid PRIMARY KEY, email text);
    CREATE TABLE public.users (id uuid PRIMARY KEY, role text);
    CREATE TABLE public.admin_whitelist (id bigint, email text);
    CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$ SELECT nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
    CREATE FUNCTION private.is_admin_reader() RETURNS boolean LANGUAGE sql SECURITY DEFINER AS $$ SELECT EXISTS(SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin') $$;
    CREATE TABLE public.inquiries (id bigint PRIMARY KEY, user_id uuid, host_id uuid, type text, status text, content text, updated_at timestamptz DEFAULT now());
    CREATE TABLE public.proxy_requests(id text PRIMARY KEY, user_id uuid, form_data jsonb);
    CREATE TABLE public.inquiry_messages (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, inquiry_id bigint REFERENCES public.inquiries(id), sender_id uuid, content text, type text DEFAULT 'text', is_read boolean DEFAULT false, read_at timestamptz, created_at timestamptz DEFAULT now());
    ALTER TABLE public.inquiries ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.inquiry_messages ENABLE ROW LEVEL SECURITY;
    CREATE POLICY participant_read ON public.inquiries FOR SELECT TO authenticated USING (auth.uid() IN (user_id, host_id));
    CREATE POLICY admin_read ON public.inquiries FOR SELECT TO authenticated USING (private.is_admin_reader());
    CREATE POLICY participant_messages ON public.inquiry_messages FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.inquiries i WHERE i.id = inquiry_id));
    CREATE POLICY "Users can update own inquiries" ON public.inquiries FOR UPDATE USING (auth.uid() IN (user_id, host_id));
    CREATE POLICY "Users can update messages in their inquiries" ON public.inquiry_messages FOR UPDATE USING (EXISTS (SELECT 1 FROM public.inquiries i WHERE i.id = inquiry_id AND auth.uid() IN (i.user_id, i.host_id)));
    GRANT USAGE ON SCHEMA public, auth, private TO anon, authenticated, service_role;
    GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
    GRANT UPDATE (content, sender_id, type, is_read, read_at) ON public.inquiry_messages TO authenticated;
    GRANT UPDATE (user_id, host_id, type, status) ON public.inquiries TO authenticated;
    GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO service_role;
    INSERT INTO public.users VALUES ('${guest}', 'guest'), ('${host}', 'host'), ('${admin}', 'admin'), ('${whitelist}', 'guest'), ('${outsider}', 'guest');
    INSERT INTO auth.users VALUES ('${whitelist}', 'staff@example.invalid'), ('${guest}', 'guest@example.invalid');
    INSERT INTO public.admin_whitelist VALUES (1, 'staff@example.invalid');
    INSERT INTO public.inquiries VALUES (1, '${guest}', '${host}', 'general', 'open', 'preview', '2026-10-01T01:00Z'), (2, '${guest}', null, 'admin_support', 'resolved', 'done', '2026-10-01T01:00Z'), (3, '${admin}', '${guest}', 'admin', 'resolved', 'legacy', '2026-10-01T01:00Z');
    INSERT INTO public.inquiry_messages (inquiry_id, sender_id, content) VALUES (1, '${host}', 'host message');
  `);
  return db;
}

export async function as(db, role, actor, sql, params = []) {
  await db.exec(`SET ROLE ${role}; SET request.jwt.claim.sub = '${actor}';`);
  try { return await db.query(sql, params); } finally { await db.exec('RESET ROLE'); }
}
