import assert from 'node:assert/strict';
import {test,after} from 'node:test';
import {mkdtemp,rm,mkdir} from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
import {build} from 'esbuild';
await mkdir('.tmp',{recursive:true});const dir=await mkdtemp(path.resolve('.tmp/host-routes-'));
let profile,registration;
try{await build({entryPoints:['app/api/host/profile/route.ts','app/api/host/register/submit/route.ts'],bundle:true,platform:'node',format:'cjs',outdir:dir,external:['next/server'],plugins:[{name:'synthetic-auth-db',setup(b){b.onResolve({filter:/utils\/supabase\/(admin|server)$/},a=>({path:a.path,namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},()=>({contents:'export const createAdminClient=()=>globalThis.__hostRouteFixture.admin;export const createClient=async()=>({auth:{getUser:async()=>({data:{user:globalThis.__hostRouteFixture.user},error:null})}});',loader:'js'}));}}]});
profile=require(dir+'/profile/route.js').POST;registration=require(dir+'/register/submit/route.js').POST;}catch(error){await rm(dir,{recursive:true,force:true});throw error;}
after(()=>rm(dir,{recursive:true,force:true}));
const owner='11111111-1111-4111-8111-111111111111';
function fixture({auth=true,race=false,status='pending'}={}){const app={id:owner,profile_photo:'https://source.test/current',status},calls=[];class Q{constructor(table){this.table=table;this.filters=[];}select(){return this;}eq(k,v){this.filters.push([k,v]);return this;}is(k,v){this.filters.push([k,v]);return this;}order(){return this;}limit(){return this;}update(v){this.value=v;calls.push({table:this.table,updates:v});return this;}async maybeSingle(){if(this.value){if(race)app.profile_photo='https://source.test/newer';return {data:this.filters.every(([k,v])=>app[k]===v)?{id:owner}:null,error:null};}assert(this.filters.some(([k,v])=>k==='user_id'&&v===owner));return {data:structuredClone(app),error:null};}then(a,b){return Promise.resolve({data:null,error:null}).then(a,b);}}globalThis.__hostRouteFixture={user:auth?{id:owner}:null,admin:{from:t=>new Q(t)}};return {app,calls};}
const req=body=>new Request('https://app.test/api/host/profile',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});
test('actual Host save requires exact browser snapshot before all writes; unauthenticated remains denied',async()=>{const f=fixture();for(const body of [{avatarUrl:'https://new.test/photo'},{avatarUrl:'https://new.test/photo',expectedProfilePhoto:'https://old.test/photo'}])assert.equal((await profile(req(body))).status,409);assert.equal(f.calls.length,0);fixture({auth:false});assert.equal((await profile(req({}))).status,401);});
test('actual Host save photo CAS protects a newer concurrent edit and never writes Account avatar',async()=>{const f=fixture({race:true});const r=await profile(req({avatarUrl:'https://new.test/photo',expectedProfilePhoto:f.app.profile_photo,fullName:'Synthetic'}));assert.equal(r.status,409);assert.equal(f.app.profile_photo,'https://source.test/newer');assert(f.calls.every(c=>!Object.hasOwn(c.updates,'avatar_url')));});
test('actual Host save accepts matching snapshot and commits only the Host locator',async()=>{const f=fixture();const r=await profile(req({avatarUrl:'https://new.test/photo',expectedProfilePhoto:f.app.profile_photo,fullName:'Synthetic'}));assert.equal(r.status,200);assert(f.calls.some(c=>c.table==='host_applications'&&c.updates.profile_photo==='https://new.test/photo'));assert(f.calls.every(c=>!Object.hasOwn(c.updates,'avatar_url')));});
test('approved registration remains immutable; pending resubmit requires exact source snapshot',async()=>{let f=fixture({status:'approved'});assert.equal((await registration(req({profilePhoto:'https://wrong.test/new'}))).status,200);assert.equal(f.calls.length,0);f=fixture();assert.equal((await registration(req({profilePhoto:'https://wrong.test/new'}))).status,409);assert.equal(f.calls.length,0);});
