'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Locale = 'ko' | 'en' | 'ja' | 'zh';

const dictionary: Record<Locale, Record<string, string>> = {
  ko: {
    // [헤더 & 네비게이션]
    host_mode: "호스트 모드로 전환",
    guest_mode: "게스트 모드로 전환",
    become_host: "호스트 등록하기",
    login: "로그인",
    logout: "로그아웃",
    signup: "회원가입",
    my_trips: "나의 여행",
    wishlist: "위시리스트",
    messages: "메시지",
    account: "계정 관리",
    help: "도움말 센터",
    notifications: "알림",

    // [메인 검색창]
    anywhere: "어디든지",
    anytime: "언제든지",
    search: "검색",
    label_destination: "여행지",
    label_date: "날짜",
    label_guest: "인원",
    search_placeholder: "여행지 검색",
    add_dates: "날짜 추가",
    add_guests: "게스트 추가",

    // [카테고리 & 도시]
    cat_exp: "체험",
    cat_service: "서비스",
    city_all: "전체",
    city_tokyo: "도쿄",
    city_osaka: "오사카",
    city_fukuoka: "후쿠오카",
    city_sapporo: "삿포로",
    city_nagoya: "나고야",
    city_seoul: "서울",
    city_busan: "부산",

    // [로그인 모달]
    welcome_title: "Locally에 오신 것을 환영합니다.",
    welcome_subtitle: "현지인처럼 여행하는 가장 쉬운 방법",
    email: "이메일",
    password: "비밀번호",
    login_button: "로그인",
    or: "또는",
    continue_kakao: "카카오톡으로 계속하기",
    continue_google: "구글로 계속하기",
    no_account: "계정이 없으신가요?",
    agree_terms: "계속 진행하면 Locally의 서비스 약관 및 개인정보 처리방침에 동의하는 것으로 간주됩니다.",

    // [푸터]
    footer_support: "로컬리 지원",
    footer_intro: "로컬리 소개",
    footer_notice: "공지사항",
    footer_help: "도움말 센터",
    footer_admin: "Admin",
    footer_hosting: "호스팅",
    footer_become_host: "호스트 되기",
    footer_community: "커뮤니티 포럼",
    footer_locally: "로컬리",
    footer_news: "뉴스",
    footer_careers: "채용 정보",
    footer_investors: "투자자 정보",
    footer_partnership: "제휴 문의",
    footer_social: "소셜",
    footer_privacy: "개인정보 처리방침",
    footer_terms: "이용약관",
    footer_travel_terms: "여행약관",
    footer_refund: "취소 및 환불 정책",
    footer_sitemap: "사이트맵",
    copyright: "© 2026 Locally, Inc."
  },
  en: {
    host_mode: "Switch to Host",
    guest_mode: "Switch to Guest",
    become_host: "Become a Host",
    login: "Log in",
    logout: "Log out",
    signup: "Sign up",
    my_trips: "Trips",
    wishlist: "Wishlist",
    messages: "Messages",
    account: "Account",
    help: "Help Center",
    notifications: "Notifications",
    anywhere: "Anywhere",
    anytime: "Anytime",
    search: "Search",
    label_destination: "Where",
    label_date: "When",
    label_guest: "Who",
    search_placeholder: "Search destinations",
    add_dates: "Add dates",
    add_guests: "Add guests",
    cat_exp: "Experiences",
    cat_service: "Services",
    city_all: "All",
    city_tokyo: "Tokyo",
    city_osaka: "Osaka",
    city_fukuoka: "Fukuoka",
    city_sapporo: "Sapporo",
    city_nagoya: "Nagoya",
    city_seoul: "Seoul",
    city_busan: "Busan",
    welcome_title: "Welcome to Locally",
    welcome_subtitle: "The easiest way to travel like a local",
    email: "Email",
    password: "Password",
    login_button: "Log in",
    or: "or",
    continue_kakao: "Continue with Kakao",
    continue_google: "Continue with Google",
    no_account: "Don't have an account?",
    agree_terms: "By continuing, you agree to Locally's Terms of Service and Privacy Policy.",
    footer_support: "Support",
    footer_intro: "About Locally",
    footer_notice: "Notices",
    footer_help: "Help Center",
    footer_admin: "Admin",
    footer_hosting: "Hosting",
    footer_become_host: "Become a Host",
    footer_community: "Community Forum",
    footer_locally: "Locally",
    footer_news: "Newsroom",
    footer_careers: "Careers",
    footer_investors: "Investors",
    footer_partnership: "Partnerships",
    footer_social: "Social",
    footer_privacy: "Privacy",
    footer_terms: "Terms",
    footer_travel_terms: "Travel Terms",
    footer_refund: "Refund Policy",
    footer_sitemap: "Sitemap",
    copyright: "© 2026 Locally, Inc."
  },
  ja: {
    host_mode: "ホストモード",
    guest_mode: "ゲストモード",
    become_host: "ホストになる",
    login: "ログイン",
    logout: "ログアウト",
    signup: "会員登録",
    my_trips: "旅行",
    wishlist: "お気に入り",
    messages: "メッセージ",
    account: "アカウント",
    help: "ヘルプ",
    notifications: "通知",
    anywhere: "どこでも",
    anytime: "いつでも",
    search: "検索",
    label_destination: "ロケーション",
    label_date: "日付",
    label_guest: "人数",
    search_placeholder: "行き先を検索",
    add_dates: "日付を追加",
    add_guests: "人数を追加",
    cat_exp: "体験",
    cat_service: "サービス",
    city_all: "すべて",
    city_tokyo: "東京",
    city_osaka: "大阪",
    city_fukuoka: "福岡",
    city_sapporo: "札幌",
    city_nagoya: "名古屋",
    city_seoul: "ソウル",
    city_busan: "釜山",
    welcome_title: "Locallyへようこそ",
    welcome_subtitle: "現地のように旅する一番簡単な方法",
    email: "メールアドレス",
    password: "パスワード",
    login_button: "ログイン",
    or: "または",
    continue_kakao: "カカオで続ける",
    continue_google: "Googleで続ける",
    no_account: "アカウントをお持ちでないですか？",
    agree_terms: "続行することで、Locallyの利用規約とプライバシーポリシーに同意したものとみなされます。",
    footer_support: "サポート",
    footer_intro: "Locallyについて",
    footer_notice: "お知らせ",
    footer_help: "ヘルプセンター",
    footer_admin: "管理者",
    footer_hosting: "ホスティング",
    footer_become_host: "ホストになる",
    footer_community: "コミュニティ",
    footer_locally: "Locally",
    footer_news: "ニュース",
    footer_careers: "採用情報",
    footer_investors: "投資家情報",
    footer_partnership: "提携のお問い合わせ",
    footer_social: "ソーシャル",
    footer_privacy: "プライバシーポリシー",
    footer_terms: "利用規約",
    footer_travel_terms: "旅行業約款",
    footer_refund: "キャンセルポリシー",
    footer_sitemap: "サイトマップ",
    copyright: "© 2026 Locally, Inc."
  },
  zh: {
    host_mode: "切换房东模式",
    guest_mode: "切换游客模式",
    become_host: "成为房东",
    login: "登录",
    logout: "退出",
    signup: "注册",
    my_trips: "行程",
    wishlist: "心愿单",
    messages: "消息",
    account: "账号",
    help: "帮助",
    notifications: "通知",
    anywhere: "任意地点",
    anytime: "任意时间",
    search: "搜索",
    label_destination: "地点",
    label_date: "日期",
    label_guest: "人数",
    search_placeholder: "搜索目的地",
    add_dates: "添加日期",
    add_guests: "添加人数",
    cat_exp: "体验",
    cat_service: "服务",
    city_all: "全部",
    city_tokyo: "东京",
    city_osaka: "大阪",
    city_fukuoka: "福冈",
    city_sapporo: "札幌",
    city_nagoya: "名古屋",
    city_seoul: "首尔",
    city_busan: "釜山",
    welcome_title: "欢迎来到 Locally",
    welcome_subtitle: "像当地人一样旅行的最简单方式",
    email: "邮箱",
    password: "密码",
    login_button: "登录",
    or: "或",
    continue_kakao: "Kakao 登录",
    continue_google: "Google 登录",
    no_account: "没有账号？",
    agree_terms: "继续即表示您同意 Locally 的服务条款和隐私政策。",
    footer_support: "支持",
    footer_intro: "关于 Locally",
    footer_notice: "公告",
    footer_help: "帮助中心",
    footer_admin: "管理员",
    footer_hosting: "出租",
    footer_become_host: "成为房东",
    footer_community: "社区论坛",
    footer_locally: "Locally",
    footer_news: "新闻",
    footer_careers: "招聘信息",
    footer_investors: "投资者",
    footer_partnership: "合作咨询",
    footer_social: "社交媒体",
    footer_privacy: "隐私政策",
    footer_terms: "服务条款",
    footer_travel_terms: "旅游条款",
    footer_refund: "退款政策",
    footer_sitemap: "网站地图",
    copyright: "© 2026 Locally, Inc."
  }
};

const LanguageContext = createContext<any>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Locale>('ko');

  useEffect(() => {
    const saved = localStorage.getItem('app_lang') as Locale;
    if (saved && dictionary[saved]) setLang(saved);
  }, []);

  const changeLang = (newLang: Locale) => {
    setLang(newLang);
    localStorage.setItem('app_lang', newLang);
  };

  const t = (key: string) => {
    return dictionary[lang]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang: changeLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);