'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Locale = 'ko' | 'en' | 'ja' | 'zh';

const dictionary: Record<Locale, Record<string, string>> = {
  ko: {
    // [1. 공통 & 헤더]
    host_mode: "호스트 모드로 전환",
    guest_mode: "게스트 모드로 전환",
    become_host: "호스트 등록하기",
    login: "로그인",
    logout: "로그아웃",
    signup: "회원가입",
    messages: "메시지",
    notifications: "알림",
    
    // [2. 카테고리 & 도시]
    cat_exp: "체험",
    cat_service: "서비스",
    city_all: "전체",
    city_tokyo: "도쿄",
    city_osaka: "오사카",
    city_fukuoka: "후쿠오카",
    city_sapporo: "삿포로",
    city_nagoya: "나고야",
    city_seoul: "서울",
    city_busan: "부산",
    city_jeju: "제주",

    // [3. 푸터]
    footer_support: "로컬리 지원",
    footer_intro: "로컬리 소개",
    footer_notice: "공지사항",
    footer_help: "도움말 센터",
    footer_admin: "Admin",
    footer_hosting: "호스팅",
    footer_become_host: "호스트 되기",
    footer_community: "커뮤니티 포럼",
    footer_locally: "로컬리",
    footer_news: "뉴스",
    footer_careers: "채용 정보",
    footer_investors: "투자자 정보",
    footer_partnership: "제휴 문의",
    footer_social: "소셜",
    footer_privacy: "개인정보 처리방침",
    footer_terms: "이용약관",
    footer_travel_terms: "여행약관",
    footer_refund: "취소 및 환불 정책",
    footer_sitemap: "사이트맵",
    copyright: "© 2026 Locally, Inc.",

    // [4. 게스트: 여행 & 위시리스트]
    my_trips: "나의 여행",
    wishlist: "위시리스트",
    wishlist_empty: "아직 찜한 체험이 없어요",
    wishlist_desc: "마음에 드는 체험을 찾아 하트를 눌러보세요!",
    explore_exp: "체험 둘러보기",
    trip_upcoming: "예정된 일정",
    trip_past: "지난 여행",
    trip_review: "후기 작성하기",
    trip_pay_date: "결제 일시",
    trip_map: "지도",
    trip_add_calendar: "캘린더에 추가",
    trip_view_again: "체험 다시 보기",
    trip_cancel_req: "예약 취소 요청",
    trip_start_in: "일 후 출발",
// [달력 - 기존 키 활용 및 월 추가]
month_1: "1월", month_2: "2월", month_3: "3월", month_4: "4월", month_5: "5월", month_6: "6월",
month_7: "7월", month_8: "8월", month_9: "9월", month_10: "10월", month_11: "11월", month_12: "12월",
select_year: "연도 선택",
confirm_date: "적용",
    per_person: "/ 인",
    receipt: "영수증",
    paid_label: "결제:",
    error_prefix: "오류:",
    trip_empty_title: "예정된 여행이 없습니다",
    trip_past_empty: "다녀온 여행 내역이 없습니다.",

    // [5. 게스트: 프로필 & 계정]
    account: "계정 관리",
    account_title: "계정 및 프로필",
    account_desc: "본인 정보를 관리하고 호스트에게 보여질 프로필을 설정하세요.",
    identity_verified: "신원 인증됨",
    review_from_host: "호스트에게 받은 후기",
    label_name: "이름 (실명)",
    label_nationality: "국적",
    select_nationality: "국적을 선택하세요",
    label_birth: "생년월일",
    label_gender: "성별",
    gender_male: "남성",
    gender_female: "여성",
    gender_other: "기타",
    label_phone: "전화번호",
    label_kakao: "카카오톡 ID (선택)",
    label_mbti: "MBTI",
    label_email: "이메일 주소",
    label_bio: "자기소개",
    btn_save_changes: "변경사항 저장",
    // 👇 여기 추가
    saving: "저장 중...",
    profile_photo_change_done: "프로필 사진이 변경되었습니다.",
    profile_photo_fail: "사진 업로드 실패:",
    profile_save_success: "프로필이 성공적으로 저장되었어요.",
    profile_save_fail: "저장에 실패했어요. 잠시 후 다시 시도해주세요.",
    label_no_name: "이름 없음",
    label_no_nationality: "국적 미설정",
    ph_phone: "+82 10-1234-5678",
    ph_kakao: "연락용 카카오톡 ID",
    ph_mbti: "ex. ENFP",
    ph_bio: "호스트에게 자신을 간단히 소개해주세요. (취미, 여행 스타일 등)",
    help_phone: "* 국적 선택 시 국가번호가 자동 입력됩니다.",
    help_email: "* 로그인 시 사용하는 ID가 변경됩니다.",
    gender_select: "선택하세요",
    host_honorific: " 호스트님",
    msg_select: "대화를 선택하세요.",
    msg_list: "대화 목록",
    // 👇 여기 추가
    msg_placeholder: "메시지 입력...",
    msg_empty: "대화가 없습니다.",
    msg_select_chat: "대화를 선택하세요.",
    admin_chat_title: "1:1 문의 (고객센터)",
    admin_name: "로컬리 고객센터",

    // [6. 호스트 대시보드]
    host_partner: "HOST PARTNER",
    host_approved: "승인된 호스트입니다",
    menu_reservation: "예약 관리",
    menu_my_exp: "내 체험 관리",
    menu_inquiry: "문의함",
    menu_earnings: "수익 및 정산",
    menu_reviews: "받은 후기",
    menu_profile: "프로필 설정",
    
    // 예약 관리
    res_status: "예약 현황",
    res_desc: "게스트의 예약을 관리하고 준비하세요.",
    tab_upcoming: "다가오는 일정",
    tab_past: "지난 일정",
    tab_cancel: "취소/환불",
    res_paid_at: "결제 일시",
    res_income: "수입 예정",
    res_people: "명 참여",
    res_cancel_req: "취소 요청됨",
    res_cancel_msg: "취소 요청이 접수되었습니다.",
    res_reason: "사유",
    res_approve_refund: "승인 및 환불",
    
    // 체험 관리 & 수익
    exp_new: "새 체험 등록",
    exp_selling: "판매중",
    exp_edit: "수정",
    exp_schedule: "일정 관리",
    earn_title: "호스팅 수입",
    earn_expected: "정산 예정 금액",
    earn_total_count: "총 건의 예약 완료",
    earn_summary: "정산 상세 내역",
    earn_gross: "총 매출",
    earn_fee: "서비스 수수료",
    earn_net: "최종 지급액",
    
    // 프로필 설정 (호스트용)
    profile_public: "공개 프로필 (게스트용)",
    profile_private: "비공개 정보 (관리용)",
    profile_job: "직업 / 직장",
    profile_dream: "꿈의 여행지",
    profile_song: "최애 노래",
    profile_lang: "구사 언어",
    profile_photo_change: "프로필 사진 변경",
    private_info_warning: "개인 정보 및 정산 정보는 직접 수정할 수 없습니다.",
    private_info_desc: "이 정보는 게스트에게 공개되지 않으며, 정산 및 본인 확인 용도로만 사용됩니다.",
    info_contact: "개인 신상 정보",
    info_bank: "정산 계좌 정보",
    bank_name: "은행명",
    bank_account: "계좌번호",
    bank_owner: "예금주",
    motivation: "지원 동기",

    // [기타]
    search: "검색",
    filter: "필터",
    confirm: "확인",
    cancel: "취소",
    loading: "로딩 중...",
    search_placeholder: "여행지 검색",
    add_dates: "날짜 추가",
    add_guests: "게스트 추가",
    login_required: "로그인이 필요합니다.",
    
    // [로그인]
    welcome_title: "Locally에 오신 것을 환영합니다.",
    welcome_subtitle: "현지인처럼 여행하는 가장 쉬운 방법",
    email: "이메일",
    password: "비밀번호",
    login_button: "로그인",
    or: "또는",
    continue_kakao: "카카오톡으로 계속하기",
    continue_google: "구글로 계속하기",
    no_account: "계정이 없으신가요?",
    agree_terms: "계속 진행하면 Locally의 서비스 약관 및 개인정보 처리방침에 동의하는 것으로 간주됩니다.",
// [언어 필터]
lang_all: "전체",
lang_ko: "한국어",
lang_en: "영어",
lang_ja: "일본어",
lang_zh: "중국어",
    // [검색창 - 누락된 키 추가]
    anywhere: "어디든지",
    anytime: "언제든지",
    label_destination: "여행지",
    label_date: "날짜",
    label_language: "언어", // 🟢 [수정] 인원 -> 언어
    add_language: "언어 추가", // 🟢 [수정] 게스트 추가 -> 언어 추가
    date_year: "년",
    date_month: "월",
    day_0: "일",
    day_1: "월",
    day_2: "화",
    day_3: "수",
    day_4: "목",
    day_5: "금",
    day_6: "토",
    // [Help Center]
    help_title: "Help Center",
    help_search_placeholder: "질문을 검색해보세요...",
    tab_guest: "게스트 (For Guests)",
    tab_host: "호스트 (For Hosts)",
    help_bottom_title: "더 궁금한 점이 있으신가요?",
    help_bottom_desc: "원하시는 답변을 찾지 못하셨나요?\n로컬리 지원팀에게 직접 문의해 보세요.",
    btn_chat_support: "1:1 채팅 문의",
    btn_email_us: "이메일 문의",
    
    // [FAQ Categories]
    faq_cat_booking: "예약 및 결제",
    faq_cat_experience: "투어 이용",
    faq_cat_cancellation: "취소 및 환불",
    faq_cat_account: "계정 관리",
    faq_cat_start: "호스트 시작하기",
    faq_cat_operation: "운영 노하우",

    // [FAQ Items - Guest]
    // 예약
    q_g_booking_1: "원하는 날짜가 안 보여요.",
    a_g_booking_1: "로컬리의 호스트들은 전문 가이드가 아닌, 본업이 있는 현지인들이라 스케줄이 유동적일 수 있습니다. 만약 달력에 원하는 날짜가 없다면 '호스트에게 문의하기'를 통해 메시지를 보내보세요! 호스트가 일정을 확인하고 시간을 조율해 드릴 수도 있습니다.",
    q_g_booking_2: "프라이빗(단독) 투어도 가능한가요?",
    a_g_booking_2: "네, 물론입니다. 예약 시 '프라이빗 투어' 옵션을 선택해 주세요. (옵션이 없는 경우 호스트에게 메시지로 문의) 호스트가 오직 당신만을 위한 체험을 준비해 드립니다.",
    q_g_booking_3: "1인 예약 확정 옵션이 무엇인가요?",
    a_g_booking_3: "기본적으로 2인 이상 모집 시 출발하지만, 혼자 여행하시는 분들을 위해 '1인 출발 확정' 옵션을 제공합니다. 추가 비용을 내고 예약하시면 인원 미달 걱정 없이 출발이 확정되며, 추후 다른 게스트가 합류하면 추가 결제하신 비용은 100% 환불됩니다.",
    q_g_booking_4: "결제 수단은 무엇을 지원하나요?",
    a_g_booking_4: "현재 국내 신용카드 및 체크카드 결제를 지원하며, 카카오페이, 네이버페이 등 간편 결제도 가능합니다. 해외 발행 카드는 비자(Visa), 마스터(Master) 카드를 지원하며 추후 더 다양한 결제 수단을 도입할 예정입니다.",
    q_g_booking_5: "일행과 따로 결제할 수 있나요?",
    a_g_booking_5: "가능합니다. 각자 예약하되, 같은 시간대를 선택해 주세요. 예약 후 호스트에게 '일행입니다'라고 메시지를 남겨주시면 함께 진행할 수 있도록 준비해 드립니다.",
    
    // 투어 이용
    q_g_exp_1: "외국어를 못하는데 참여할 수 있나요?",
    a_g_exp_1: "걱정하지 마세요! 언어 장벽 없이 편안하게 즐기실 수 있습니다. 로컬리 호스트와의 모든 소통은 당신의 언어로 이루어지니 안심하세요.",
    q_g_exp_2: "호스트와 연락은 어떻게 하나요?",
    a_g_exp_2: "예약이 확정되면 '메시지' 탭에서 호스트와 1:1 대화방이 열립니다. 투어 장소, 준비물, 시간 등 궁금한 점을 자유롭게 물어보세요.",
    q_g_exp_3: "투어 당일 지각하면 어떻게 되나요?",
    a_g_exp_3: "투어는 정해진 시간에 출발하므로 지각 시 참여가 어려울 수 있으며, 이 경우 당일 취소로 간주되어 환불이 불가합니다. 늦을 것 같다면 반드시 호스트에게 미리 연락해 주세요.",
    q_g_exp_4: "식사나 음료 비용은 포함인가요?",
    a_g_exp_4: "대부분의 투어에는 식비가 포함되어 있지 않습니다. 현지 맛집을 탐방하며 각자 주문한 메뉴를 결제하거나, 호스트가 먼저 결제하고 투어 종료 시 정산(더치페이)하는 방식을 주로 사용합니다. 예약 전 '포함 사항'을 꼭 확인해 주세요.",
    q_g_exp_5: "사진 촬영이 가능한가요?",
    a_g_exp_5: "자유롭게 촬영하셔도 좋습니다! 호스트에게 인생샷을 부탁해 보세요. 단, 미술관 내부나 특정 상점 등 촬영이 제한된 구역에서는 호스트의 안내를 따라 주시고, 타인의 초상권은 지켜주시는 센스 부탁드립니다.",
    q_g_exp_6: "고령자나 아이도 참여할 수 있나요?",
    a_g_exp_6: "네, 남녀노소 누구나 환영합니다. 다만 많이 걷는 투어거나 술을 마시는 투어의 경우 제한이 있을 수 있습니다. 동반자가 있다면 호스트에게 미리 메시지를 보내주세요. 걷기 편한 코스로 조정하거나 아이를 위한 배려를 준비해 드릴 수 있습니다.",
    q_g_exp_7: "투어 중 화장실 이용이나 휴식은?",
    a_g_exp_7: "로컬리 투어는 패키지여행처럼 빡빡하지 않습니다. 걷다가 힘들거나 화장실이 급하면 언제든 호스트에게 말씀해 주세요. 현지인만 아는 깨끗한 화장실 위치나 분위기 좋은 벤치에서 잠시 쉬어갈 수 있습니다.",
    
    // 취소 환불
    q_g_cancel_1: "투어 당일 지각하면 어떻게 되나요?",
    a_g_cancel_1: "투어는 정해진 시간에 출발하므로 늦으실 경우 참여가 어려울 수 있습니다. (당일 취소/환불 불가) 약속 시간 10분 전 도착을 권장하며, 늦을 것 같다면 반드시 호스트에게 미리 연락해 주세요.",
    q_g_cancel_2: "우천 시 투어는 어떻게 되나요?",
    a_g_cancel_2: "약한 비에는 낭만적인 우중 투어로 진행됩니다. 하지만 태풍 등 안전이 우려되는 악천후 시에는 호스트 판단하에 취소될 수 있으며, 이 경우 수수료 없이 100% 전액 환불해 드립니다.",
    q_g_cancel_3: "환불 규정이 궁금해요.",
    a_g_cancel_3: "투어일 기준 20일 전 100%, 7일 전 70%, 1일 전 40% 환불되며 당일 취소는 환불이 불가합니다. 호스트 사유로 취소될 경우 시점에 관계없이 전액 환불됩니다.",
    q_g_cancel_4: "예약을 취소하면 언제 환불되나요?",
    a_g_cancel_4: "취소 요청 후 시스템에서 처리가 완료되면 즉시 카드사로 취소 요청이 전송됩니다. 카드사에 따라 영업일 기준 3~5일 정도 소요될 수 있습니다. 체크카드의 경우 보통 2일 이내에 입금됩니다.",
    q_g_cancel_5: "날짜 변경은 가능한가요?",
    a_g_cancel_5: "예약 확정 후 날짜 변경은 원칙적으로 불가능하며, 기존 예약을 취소하고 다시 예약하셔야 합니다. 이 경우 기존 예약 취소 시점에 따른 환불 수수료가 발생할 수 있으니 주의해 주세요.",

    // 계정 관리
    q_g_account_1: "호스트는 믿을 수 있는 사람인가요?",
    a_g_account_1: "로컬리의 모든 호스트는 엄격한 신원 인증(본인 확인, 전화번호 인증, 계좌 점유 인증)을 거칩니다. 또한, 실제 투어 참여 게스트들의 솔직한 후기로 평판이 투명하게 관리되고 있어 안심하셔도 됩니다.",
    q_g_account_2: "비밀번호를 잊어버렸어요.",
    a_g_account_2: "로그인 화면 하단의 '비밀번호 찾기'를 통해 이메일 인증 후 재설정하실 수 있습니다.",
    q_g_account_3: "회원 탈퇴는 어떻게 하나요?",
    a_g_account_3: "마이페이지 > 계정 설정 하단에서 탈퇴 가능합니다. 탈퇴 시 모든 여행 기록과 쿠폰은 소멸되며 복구할 수 없습니다.",

    // [FAQ Items - Host]
    // 호스트 시작
    q_h_start_1: "호스트 등록 조건이 있나요?",
    a_h_start_1: "자격증은 필요 없습니다! 현지에 거주하며 나만의 취향과 이야기를 공유하고 싶은 분이라면 누구나 환영합니다. 맛집 탐방, 산책, 쇼핑 등 당신의 일상이 누군가에게는 특별한 여행이 됩니다.",
    q_h_start_2: "등록 비용이 드나요?",
    a_h_start_2: "아니요, 호스트 등록 및 투어 상품 등록은 전액 무료입니다. 예약이 확정되어 수익이 발생할 때만 소정의 수수료가 부과됩니다.",
    q_h_start_3: "수수료는 얼마인가요?",
    a_h_start_3: "로컬리 플랫폼 수수료는 예약 금액의 20%입니다. 이 수수료에는 결제 대행 수수료, 서버 유지비, 마케팅 비용, 세금, 부가 비용 등이 포함되어 있습니다.",
    q_h_start_4: "수익은 얼마나 되나요?",
    a_h_start_4: "투어 요금은 호스트님이 직접 설정합니다. 인기 호스트의 경우 월 수백만 원의 부수입을 올리기도 합니다. 로컬리 수수료(20%)를 제외한 금액이 정산됩니다.",
    q_h_start_5: "외국어를 잘해야 하나요?",
    a_h_start_5: "외국인 대상 투어라면 필수지만, 한국인 여행자를 대상으로 한다면 한국어만 하셔도 충분합니다. 언어 능력보다는 친절함과 현지 지식이 더 중요합니다.",
    q_h_start_6: "어떤 투어를 만들 수 있나요?",
    a_h_start_6: "맛집 투어, 골목 산책, 등산, 쿠킹 클래스, 사진 촬영 등 현지에서 할 수 있는 모든 활동이 가능합니다. 거창하지 않아도 됩니다. 현지인만 아는 '진짜' 경험을 공유해 주세요.",
    q_h_start_7: "프로필 사진은 꼭 본인이어야 하나요?",
    a_h_start_7: "네, 게스트에게 신뢰를 주기 위해 본인의 얼굴이 잘 나온 사진을 권장합니다. 풍경이나 동물 사진보다는, 호스트님의 밝은 미소가 담긴 사진이 예약률을 높이는 데 도움이 됩니다.",
    q_h_start_8: "정산은 언제 되나요?",
    a_h_start_8: "투어가 완료된 날짜를 기준으로, 4주 후 등록하신 계좌로 일괄 입금됩니다. (공휴일인 경우 그 다음 영업일 지급)",
    q_h_start_9: "해외 거주자도 등록 가능한가요?",
    a_h_start_9: "네, 전 세계 어디서든 로컬리 호스트로 활동하실 수 있습니다. 해외 계좌로 정산을 받으실 경우 페이팔(PayPal), 라인(Line), 또는 와이즈(Wise) 연동이 필요할 수 있습니다.",

    // 운영 노하우
    q_h_oper_1: "일정 관리는 어떻게 하나요?",
    a_h_oper_1: "호스트 대시보드에서 가능한 날짜와 시간만 열어두시면 됩니다. 본업이 바쁠 때는 언제든 예약을 막아두실 수 있어 유연한 활동이 가능합니다.",
    q_h_oper_2: "최소 출발 인원은 어떻게 설정하나요?",
    a_h_oper_2: "상품 등록 시 ‘1인 출발 확정 금액’을 설정할 수 있습니다.",
    q_h_oper_3: "게스트와 연락은 어떻게 하나요?",
    a_h_oper_3: "개인 연락처 노출 없이, 로컬리 앱 내 '1:1 메시지' 기능을 통해 안전하게 소통합니다. 예약 확정 전에도 문의 메시지를 받을 수 있습니다.",
    q_h_oper_4: "노쇼(No-Show)가 발생하면요?",
    a_h_oper_4: "걱정 마세요. 예약 확정 시 결제가 완료되므로, 게스트가 나타나지 않더라도 규정에 따라 정산금을 지급받으실 수 있습니다.",
    q_h_oper_5: "진상 게스트는 어떻게 대처하나요?",
    a_h_oper_5: "투어 진행 중 무례하거나 안전을 위협하는 행동을 하는 게스트가 있다면 즉시 로컬리 고객센터로 신고해 주세요. 사실 확인 후 해당 게스트의 이용 제한 조치를 취하며, 호스트님을 보호하기 위해 최선을 다하겠습니다.",
    // [예약 관리 - 추가]
    res_empty_title: "예약 내역이 없습니다.",
    res_empty_upcoming: "매력적인 체험을 등록하고 첫 손님을 맞이해보세요!",
    res_empty_cancelled: "취소된 예약이 없습니다. (좋은 소식이네요!)",
    res_empty_date: "해당 기간의 예약 내역이 없습니다.",
    res_toast_new: "🎉 새로운 예약이 도착했습니다!",
    res_toast_cancel: "🚨 예약 취소 요청이 접수되었습니다.",
    res_error_load: "예약 정보를 불러오는데 실패했습니다.",
    res_cancel_confirm_msg: "'확인'을 누르면 채팅방으로 이동합니다.",
    res_cancel_ask: "게스트에게 직접 취소를 요청하시겠습니까?",
    res_refund_confirm_prefix: "'",
    res_refund_confirm_suffix: "' 님의 취소를 승인하고 환불하시겠습니까?",
    res_toast_approved: "취소가 승인되었습니다."
  },
  
  // 🟢 영어 (English)
  en: {
    host_mode: "Switch to Host",
    guest_mode: "Switch to Guest",
    become_host: "Become a Host",
    login: "Log in",
    logout: "Log out",
    signup: "Sign up",
    messages: "Messages",
    notifications: "Notifications",
    cat_exp: "Experiences",
    cat_service: "Services",
    city_all: "All",
    city_tokyo: "Tokyo",
    city_osaka: "Osaka",
    city_fukuoka: "Fukuoka",
    city_sapporo: "Sapporo",
    city_nagoya: "Nagoya",
    city_seoul: "Seoul",
    city_busan: "Busan",
    city_jeju: "Jeju",
    footer_support: "Support",
    footer_intro: "About Locally",
    footer_notice: "Notices",
    footer_help: "Help Center",
    footer_admin: "Admin",
    footer_hosting: "Hosting",
    footer_become_host: "Become a Host",
    footer_community: "Community Forum",
    footer_locally: "Locally",
    footer_news: "Newsroom",
    footer_careers: "Careers",
    footer_investors: "Investors",
    footer_partnership: "Partnerships",
    footer_social: "Social",
    footer_privacy: "Privacy Policy",
    footer_terms: "Terms of Service",
    footer_travel_terms: "Travel Terms",
    footer_refund: "Refund Policy",
    footer_sitemap: "Sitemap",
    copyright: "© 2026 Locally, Inc.",
    my_trips: "Trips",
    wishlist: "Wishlist",
    wishlist_empty: "No saved experiences yet",
    wishlist_desc: "Find experiences you love and tap the heart!",
    explore_exp: "Explore Experiences",
    trip_upcoming: "Upcoming",
    trip_past: "Past",
    trip_review: "Write a Review",
    trip_pay_date: "Payment Date",
    trip_map: "Map",
    receipt: "Receipt",
    paid_label: "Payment:",
    trip_add_calendar: "Add to Calendar",
    trip_view_again: "View Experience",
    trip_cancel_req: "Request Cancellation",
    trip_start_in: "days to go",
    month_1: "January", month_2: "February", month_3: "March", month_4: "April", month_5: "May", month_6: "June",
    month_7: "July", month_8: "August", month_9: "September", month_10: "October", month_11: "November", month_12: "December",
    day_0: "Sun", day_1: "Mon", day_2: "Tue", day_3: "Wed", day_4: "Thu", day_5: "Fri", day_6: "Sat",
    select_year: "Select Year",
    confirm_date: "Confirm",
    per_person: "/ person",
    // 👇 여기 추가
    error_prefix: "Error:",
    trip_empty_title: "No upcoming trips",
    trip_past_empty: "No past trips found.",
    account: "Account",
    account_title: "Profile & Account",
    account_desc: "Manage your info and set up your public profile.",
    identity_verified: "Identity Verified",
    review_from_host: "Reviews from Hosts",
    label_name: "Name (Legal)",
    label_nationality: "Nationality",
    select_nationality: "Select Nationality",
    label_birth: "Date of Birth",
    label_gender: "Gender",
    gender_male: "Male",
    gender_female: "Female",
    gender_other: "Other",
    label_phone: "Phone Number",
    label_kakao: "KakaoTalk ID",
    label_mbti: "MBTI",
    label_email: "Email Address",
    label_bio: "About Me",
    btn_save_changes: "Save Changes",
    // 👇 여기 추가
    saving: "Saving...",
    profile_photo_change_done: "Profile photo updated.",
    profile_photo_fail: "Upload failed:",
    profile_save_success: "Profile saved successfully.",
    profile_save_fail: "Failed to save. Please try again.",
    label_no_name: "No Name",
    label_no_nationality: "Nationality not set",
    ph_phone: "+1 123-456-7890",
    ph_kakao: "KakaoTalk ID for contact",
    ph_mbti: "e.g. ENFP",
    ph_bio: "Introduce yourself to the host (hobbies, travel style, etc.)",
    help_phone: "* Country code is auto-filled when selecting nationality.",
    help_email: "* Your login ID will be changed.",
    gender_select: "Select",
    host_honorific: " (Host)",
    msg_select: "Select a conversation",
    msg_list: "Messages",
    // 👇 여기 추가
    msg_placeholder: "Type a message...",
    msg_empty: "No messages yet.",
    msg_select_chat: "Select a conversation.",
    admin_chat_title: "Support Chat",
    admin_name: "Locally Support",
    host_partner: "HOST PARTNER",
    host_approved: "Approved Host",
    menu_reservation: "Reservations",
    menu_my_exp: "My Experiences",
    menu_inquiry: "Inquiries",
    menu_earnings: "Earnings",
    menu_reviews: "Reviews",
    menu_profile: "Profile Settings",
    res_status: "Reservation Status",
    res_desc: "Manage and prepare for guest reservations.",
    tab_upcoming: "Upcoming",
    tab_past: "Completed",
    tab_cancel: "Cancelled",
    res_paid_at: "Paid at",
    res_income: "Est. Income",
    res_people: "guest(s)",
    res_cancel_req: "Cancellation Requested",
    res_cancel_msg: "Cancellation request received.",
    res_reason: "Reason",
    res_approve_refund: "Approve & Refund",
    exp_new: "Create New",
    exp_selling: "Active",
    exp_edit: "Edit",
    exp_schedule: "Schedule",
    earn_title: "Hosting Earnings",
    earn_expected: "Payout Amount",
    earn_total_count: "Total Bookings",
    earn_summary: "Payout Details",
    earn_gross: "Gross Revenue",
    earn_fee: "Service Fee",
    earn_net: "Net Payout",
    profile_public: "Public Profile",
    profile_private: "Private Info",
    profile_job: "Job",
    profile_dream: "Dream Destination",
    profile_song: "Favorite Song",
    profile_lang: "Languages",
    profile_photo_change: "Change Photo",
    private_info_warning: "Private information cannot be edited directly.",
    private_info_desc: "This info is for verification and payouts only.",
    info_contact: "Personal Info",
    info_bank: "Payout Method",
    bank_name: "Bank Name",
    bank_account: "Account Number",
    bank_owner: "Account Holder",
    motivation: "Motivation",
    search: "Search",
    filter: "Filter",
    confirm: "Confirm",
    cancel: "Cancel",
    loading: "Loading...",
    search_placeholder: "Where to?",
    add_dates: "Add dates",
    add_guests: "Add guests",
    login_required: "Login required.",
    welcome_title: "Welcome to Locally",
    welcome_subtitle: "The easiest way to travel like a local",
    email: "Email",
    password: "Password",
    login_button: "Log in",
    or: "or",
    continue_kakao: "Continue with Kakao",
    continue_google: "Continue with Google",
    no_account: "Don't have an account?",
    agree_terms: "By continuing, you agree to our Terms and Privacy Policy.",
    anywhere: "Anywhere",
    anytime: "Anytime",
    label_destination: "Where",
    label_date: "When",
    label_language: "Language",
    lang_all: "All",
    lang_ko: "Korean",
    lang_en: "English",
    lang_ja: "Japanese",
    lang_zh: "Chinese",
    add_language: "Add language",
    date_year: ".",
    date_month: ".",
    // [Help Center]
    help_title: "Help Center",
    help_search_placeholder: "Search for answers...",
    tab_guest: "For Guests",
    tab_host: "For Hosts",
    help_bottom_title: "Need more help?",
    help_bottom_desc: "Can't find what you're looking for?\nContact our support team directly.",
    btn_chat_support: "Chat Support",
    btn_email_us: "Email Us",

    // [FAQ Categories]
    faq_cat_booking: "Booking & Payment",
    faq_cat_experience: "Experience",
    faq_cat_cancellation: "Cancellation & Refund",
    faq_cat_account: "Account",
    faq_cat_start: "Start Hosting",
    faq_cat_operation: "Operation",

    // [FAQ Items - Guest]
    q_g_booking_1: "I can't see the date I want.",
    a_g_booking_1: "Locally hosts are locals with main jobs, so schedules may vary. If you don't see a date, message the host! They might be able to adjust their schedule for you.",
    q_g_booking_2: "Is a private tour available?",
    a_g_booking_2: "Yes! Select the 'Private Tour' option when booking. If not available, message the host. They can prepare a customized experience just for you.",
    q_g_booking_3: "What is the 'Guaranteed Departure for 1 Person' option?",
    a_g_booking_3: "Tours usually require 2+ people. This option guarantees departure for solo travelers for an extra fee. If others join later, the extra fee is 100% refunded.",
    q_g_booking_4: "What payment methods are supported?",
    a_g_booking_4: "We support credit/debit cards (Visa, Master) and simple payments like KakaoPay. More methods coming soon.",
    q_g_booking_5: "Can I pay separately from my group?",
    a_g_booking_5: "Yes. Book separately for the same time slot, then message the host saying 'We are a group'.",

    q_g_exp_1: "I don't speak the language. Can I join?",
    a_g_exp_1: "Don't worry! You can enjoy the tour without language barriers. All communication with Locally hosts is supported in your language.",
    q_g_exp_2: "How do I contact the host?",
    a_g_exp_2: "Once booked, a 1:1 chat opens in the 'Messages' tab. Feel free to ask about meeting points, preparations, etc.",
    q_g_exp_3: "What if I'm late?",
    a_g_exp_3: "Tours start on time. Late arrival may result in being unable to join (considered a same-day cancellation, no refund). Please contact the host in advance if you're running late.",
    q_g_exp_4: "Are meals/drinks included?",
    a_g_exp_4: "Most tours don't include meal costs. You can pay for your own orders or split the bill with the host at the end. Check 'Included' details before booking.",
    q_g_exp_5: "Can I take photos?",
    a_g_exp_5: "Yes! Ask the host for a photo. However, please follow guidelines in restricted areas (e.g., museums) and respect others' privacy.",
    q_g_exp_6: "Can seniors or children join?",
    a_g_exp_6: "Everyone is welcome! However, some tours (walking-heavy, alcohol) may have restrictions. Message the host in advance to check or request adjustments.",
    q_g_exp_7: "Restrooms or breaks during the tour?",
    a_g_exp_7: "Locally tours are flexible. Tell the host anytime if you need a break or a restroom. They know the best spots.",

    q_g_cancel_1: "What if I'm late on the day?",
    a_g_cancel_1: "Tours start on time. Late arrival means no joining (no refund). Please arrive 10 mins early or contact the host ASAP.",
    q_g_cancel_2: "What if it rains?",
    a_g_cancel_2: "Light rain? The tour goes on! In severe weather (typhoon, etc.), the host may cancel for safety. In this case, you get a 100% refund.",
    q_g_cancel_3: "Refund policy?",
    a_g_cancel_3: "20 days before: 100%, 7 days: 70%, 1 day: 40%. Same-day cancellation: No refund. Host cancellation: 100% refund.",
    q_g_cancel_4: "When do I get my refund?",
    a_g_cancel_4: "Refund processing starts immediately upon approval. It may take 3-5 business days depending on your card issuer.",
    q_g_cancel_5: "Can I change the date?",
    a_g_cancel_5: "Date changes aren't possible after confirmation. Please cancel and re-book. Cancellation fees may apply.",

    q_g_account_1: "Is the host reliable?",
    a_g_account_1: "All Locally hosts undergo strict identity verification. Plus, their reputation is transparently managed via reviews from real guests.",
    q_g_account_2: "I forgot my password.",
    a_g_account_2: "Click 'Forgot Password' on the login screen to reset it via email.",
    q_g_account_3: "How do I delete my account?",
    a_g_account_3: "Go to Account Settings > Delete Account. All data and coupons will be permanently deleted.",

    // [FAQ Items - Host]
    q_h_start_1: "Requirements to be a host?",
    a_h_start_1: "No license needed! Any local wanting to share their lifestyle is welcome. Your daily life (shopping, hiking) can be a special trip for someone.",
    q_h_start_2: "Is there a registration fee?",
    a_h_start_2: "No, it's free. A small commission fee applies only when a booking is confirmed and you earn revenue.",
    q_h_start_3: "How much is the commission?",
    a_h_start_3: "Locally's platform fee is 20%. This covers payment fees, server costs, marketing, tax, etc.",
    q_h_start_4: "How much can I earn?",
    a_h_start_4: "You set the price. Popular hosts earn significant side income. You get paid the amount minus the 20% fee.",
    q_h_start_5: "Must I speak a foreign language?",
    a_h_start_5: "Required for foreign guests, but Korean is enough for Korean guests. Kindness and local knowledge matter more.",
    q_h_start_6: "What kind of tours can I make?",
    a_h_start_6: "Food tours, walks, hiking, cooking, photography... anything local! It doesn't have to be grand. Share 'real' local experiences.",
    q_h_start_7: "Must I use my own photo?",
    a_h_start_7: "Yes. A clear photo of your smiling face builds trust and increases booking rates.",
    q_h_start_8: "When do I get paid?",
    a_h_start_8: "Payouts are made 4 weeks after the tour date to your registered account.",
    q_h_start_9: "Can I host if I live abroad?",
    a_h_start_9: "Yes! You can host anywhere. For payouts, you may need PayPal, Line Pay, or Wise.",

    q_h_oper_1: "How to manage schedules?",
    a_h_oper_1: "Open only the dates/times you're available on the dashboard. You can block dates anytime.",
    q_h_oper_2: "How to set min. participants?",
    a_h_oper_2: "You can set a 'Guaranteed Departure Price for 1 Person' when registering a tour.",
    q_h_oper_3: "How to contact guests?",
    a_h_oper_3: "Use the in-app 1:1 chat safely without revealing personal contacts.",
    q_h_oper_4: "What if a guest is a No-Show?",
    a_h_oper_4: "Don't worry. You will still receive the payout according to the policy since payment is completed upon booking.",
    q_h_oper_5: "How to handle rude guests?",
    a_h_oper_5: "Report them immediately to support. We will verify facts and restrict their usage to protect you.",
    // [Reservation - Add]
    res_empty_title: "No reservations found.",
    res_empty_upcoming: "Register an experience and welcome your first guest!",
    res_empty_cancelled: "No canceled reservations. (That's good news!)",
    res_empty_date: "No reservations found for this period.",
    res_toast_new: "🎉 New booking arrived!",
    res_toast_cancel: "🚨 Cancellation request received.",
    res_error_load: "Failed to load reservations.",
    res_cancel_confirm_msg: "Press 'OK' to go to the chat room.",
    res_cancel_ask: "Ask the guest to cancel directly?",
    res_refund_confirm_prefix: "Approve cancellation and refund for '",
    res_refund_confirm_suffix: "'?",
    res_toast_approved: "Cancellation approved."
  },

  // 🟢 일본어 (Japanese)
  ja: {
    host_mode: "ホストモード",
    guest_mode: "ゲストモード",
    become_host: "ホストになる",
    login: "ログイン",
    logout: "ログアウト",
    signup: "会員登録",
    messages: "メッセージ",
    notifications: "通知",
    cat_exp: "体験",
    cat_service: "サービス",
    city_all: "すべて",
    city_tokyo: "東京",
    city_osaka: "大阪",
    city_fukuoka: "福岡",
    city_sapporo: "札幌",
    city_nagoya: "名古屋",
    city_seoul: "ソウル",
    city_busan: "釜山",
    city_jeju: "済州",
    footer_support: "サポート",
    footer_intro: "Locallyについて",
    footer_notice: "お知らせ",
    footer_help: "ヘルプセンター",
    footer_admin: "管理者",
    footer_hosting: "ホスティング",
    footer_become_host: "ホストになる",
    footer_community: "コミュニティ",
    footer_locally: "Locally",
    footer_news: "ニュース",
    footer_careers: "採用情報",
    footer_investors: "投資家情報",
    footer_partnership: "提携のお問い合わせ",
    footer_social: "ソーシャル",
    footer_privacy: "プライバシーポリシー",
    footer_terms: "利用規約",
    footer_travel_terms: "旅行業約款",
    footer_refund: "キャンセルポリシー",
    footer_sitemap: "サイトマップ",
    copyright: "© 2026 Locally, Inc.",
    my_trips: "旅行",
    wishlist: "お気に入り",
    wishlist_empty: "まだお気に入りがありません",
    wishlist_desc: "気になる体験を見つけてハートを押しましょう！",
    explore_exp: "体験を探す",
    trip_upcoming: "今後の予定",
    trip_past: "過去の旅行",
    trip_review: "レビューを書く",
    trip_pay_date: "決済日時",
    trip_map: "地図",
    receipt: "領収書",
    paid_label: "決済:",
    trip_add_calendar: "カレンダーに追加",
    trip_view_again: "体験を見る",
    trip_cancel_req: "キャンセルリクエスト",
    trip_start_in: "日後に出発",
    month_1: "1月", month_2: "2月", month_3: "3月", month_4: "4月", month_5: "5月", month_6: "6月",
    month_7: "7月", month_8: "8月", month_9: "9月", month_10: "10月", month_11: "11月", month_12: "12月",
    day_0: "日", day_1: "月", day_2: "火", day_3: "水", day_4: "木", day_5: "金", day_6: "土",
    select_year: "年を選択",
    confirm_date: "適用",
    per_person: "/ 人",
    // 👇 여기 추가
    error_prefix: "エラー:",
    trip_empty_title: "予定された旅行はありません",
    trip_past_empty: "過去の旅行履歴がありません。",
    account: "アカウント",
    account_title: "プロフィール設定",
    account_desc: "個人情報を管理し、ホストに公開するプロフィールを設定します。",
    identity_verified: "本人確認済み",
    review_from_host: "ホストからのレビュー",
    label_name: "名前 (実名)",
    label_nationality: "国籍",
    select_nationality: "国籍を選択",
    label_birth: "生年月日",
    label_gender: "性別",
    gender_male: "男性",
    gender_female: "女性",
    gender_other: "その他",
    label_phone: "電話番号",
    label_kakao: "カカオトークID",
    label_mbti: "MBTI",
    label_email: "メールアドレス",
    label_bio: "自己紹介",
    btn_save_changes: "変更を保存",
    // 👇 여기 추가
    saving: "保存中...",
    profile_photo_change_done: "プロフィール写真が変更されました。",
    profile_photo_fail: "アップロード失敗:",
    profile_save_success: "プロフィールが保存されました。",
    profile_save_fail: "保存に失敗しました。もう一度お試しください。",
    label_no_name: "名前なし",
    label_no_nationality: "国籍未設定",
    ph_phone: "+81 90-1234-5678",
    ph_kakao: "連絡用カカオトークID",
    ph_mbti: "例: ENFP",
    ph_bio: "ホストに自己紹介してください（趣味、旅行スタイルなど）",
    help_phone: "* 国籍を選択すると国番号が自動入力されます。",
    help_email: "* ログインIDが変更されます。",
    gender_select: "選択してください",
    host_honorific: " ホスト",
    msg_select: "会話を選択してください",
    msg_list: "メッセージ一覧",
    // 👇 여기 추가
    msg_placeholder: "メッセージを入力...",
    msg_empty: "メッセージがありません。",
    msg_select_chat: "会話を選択してください。",
    admin_chat_title: "1:1 お問い合わせ",
    admin_name: "Locallyサポート",
    host_partner: "HOST PARTNER",
    host_approved: "承認されたホスト",
    menu_reservation: "予約管理",
    menu_my_exp: "体験管理",
    menu_inquiry: "お問い合わせ",
    menu_earnings: "収益・精算",
    menu_reviews: "レビュー",
    menu_profile: "設定",
    res_status: "予約状況",
    res_desc: "ゲストの予約を管理・準備しましょう。",
    tab_upcoming: "予定",
    tab_past: "完了",
    tab_cancel: "キャンセル",
    res_paid_at: "決済日時",
    res_income: "収益予定",
    res_people: "名参加",
    res_cancel_req: "キャンセル申請あり",
    res_cancel_msg: "キャンセルリクエストが届きました。",
    res_reason: "理由",
    res_approve_refund: "承認して返金",
    exp_new: "新規登録",
    exp_selling: "販売中",
    exp_edit: "編集",
    exp_schedule: "日程管理",
    earn_title: "ホスティング収益",
    earn_expected: "精算予定額",
    earn_total_count: "総予約数",
    earn_summary: "詳細内訳",
    earn_gross: "総売上",
    earn_fee: "手数料",
    earn_net: "最終振込額",
    profile_public: "公開プロフィール",
    profile_private: "非公開情報",
    profile_job: "職業",
    profile_dream: "夢の旅行先",
    profile_song: "好きな曲",
    profile_lang: "使用言語",
    profile_photo_change: "写真変更",
    private_info_warning: "個人情報および精算情報は直接修正できません。",
    private_info_desc: "この情報は本人確認および精算のためにのみ使用されます。",
    info_contact: "個人情報",
    info_bank: "口座情報",
    bank_name: "銀行名",
    bank_account: "口座番号",
    bank_owner: "口座名義",
    motivation: "志望動機",
    search: "検索",
    filter: "フィルター",
    confirm: "確認",
    cancel: "キャンセル",
    loading: "読み込み中...",
    search_placeholder: "行き先を検索",
    add_dates: "日付を追加",
    add_guests: "人数を追加",
    login_required: "ログインが必要です。",
    welcome_title: "Locallyへようこそ",
    welcome_subtitle: "現地のように旅する一番簡単な方法",
    email: "メールアドレス",
    password: "パスワード",
    login_button: "ログイン",
    or: "または",
    continue_kakao: "カカオで続ける",
    continue_google: "Googleで続ける",
    no_account: "アカウントをお持ちでないですか？",
    agree_terms: "続行することで、利用規約とプライバシーポリシーに同意したものとみなされます。",
    anywhere: "どこでも",
    anytime: "いつでも",
    label_destination: "ロケーション",
    label_date: "日付",
    label_language: "言語", // 🟢 [수정] Guest -> Language
    lang_all: "すべて",
    lang_ko: "韓国語",
    lang_en: "英語",
    lang_ja: "日本語",
    lang_zh: "中国語",
    add_language: "言語を追加", // 🟢 [수정] Add guests -> Add language
    date_year: "年",
    date_month: "月",
    // [Help Center]
    help_title: "ヘルプセンター",
    help_search_placeholder: "質問を検索...",
    tab_guest: "ゲスト (For Guests)",
    tab_host: "ホスト (For Hosts)",
    help_bottom_title: "他にヘルプが必要ですか？",
    help_bottom_desc: "お探しの回答が見つかりませんか？\nLocallyサポートチームに直接お問い合わせください。",
    btn_chat_support: "チャットサポート",
    btn_email_us: "メールで問い合わせ",
    
    // [FAQ Categories]
    faq_cat_booking: "予約・決済",
    faq_cat_experience: "ツアー利用",
    faq_cat_cancellation: "キャンセル・返金",
    faq_cat_account: "アカウント管理",
    faq_cat_start: "ホストを始める",
    faq_cat_operation: "運営ノウハウ",

    // [FAQ Items - Guest]
    // 予約
    q_g_booking_1: "希望の日程が表示されません。",
    a_g_booking_1: "Locallyのホストはプロのガイドではなく、本業を持つ現地の方々であるため、スケジュールが流動的な場合があります。カレンダーに希望の日付がない場合は、「ホストに問い合わせる」からメッセージを送ってみてください！ホストが日程を確認し、時間を調整できる場合もあります。",
    q_g_booking_2: "プライベート（貸切）ツアーも可能ですか？",
    a_g_booking_2: "はい、もちろんです。予約時に「プライベートツアー」オプションを選択してください。（オプションがない場合はホストにメッセージで相談）ホストがあなただけのための体験をご用意します。",
    q_g_booking_3: "「1人出発確定」オプションとは何ですか？",
    a_g_booking_3: "基本的には2名以上で催行されますが、一人旅の方のために「1人出発確定」オプションを提供しています。追加料金を支払うことで人数不足によるキャンセルの心配なく出発が確定し、後で他のゲストが参加した場合は追加料金が100%返金されます。",
    q_g_booking_4: "決済方法は何に対応していますか？",
    a_g_booking_4: "現在、韓国国内のクレジットカードおよびチェックカード、KakaoPay、NaverPayなどの簡易決済に対応しています。海外発行カードはVisa、Masterカードに対応しており、今後さらに多様な決済手段を導入する予定です。",
    q_g_booking_5: "同行者と別々に決済できますか？",
    a_g_booking_5: "可能です。各自で予約し、同じ時間帯を選択してください。予約後、ホストに「同行者です」とメッセージを送っていただければ、スムーズに進行できるよう準備いたします。",
    
    // ツアー利用
    q_g_exp_1: "外国語が話せなくても参加できますか？",
    a_g_exp_1: "心配しないでください！言語の壁を感じることなく快適にお楽しみいただけます。Locallyホストとのすべてのコミュニケーションは、あなたの言語で行われますのでご安心ください。",
    q_g_exp_2: "ホストへの連絡方法は？",
    a_g_exp_2: "予約が確定すると、「メッセージ」タブでホストとの1:1チャットルームが開きます。集合場所、持ち物、時間など、気になることは自由に質問してください。",
    q_g_exp_3: "ツアー当日に遅刻したらどうなりますか？",
    a_g_exp_3: "ツアーは定刻に出発するため、遅刻された場合は参加できない可能性があり、その場合は当日キャンセルとみなされ返金はできません。遅れそうな場合は必ずホストに事前に連絡してください。",
    q_g_exp_4: "食事や飲み物代は含まれていますか？",
    a_g_exp_4: "ほとんどのツアーには食費が含まれていません。現地の美味しいお店を巡りながら各自注文したメニューを決済するか、ホストがまとめて決済しツアー終了後に精算（割り勘）する方式が一般的です。予約前に「含まれるもの」を必ず確認してください。",
    q_g_exp_5: "写真撮影は可能ですか？",
    a_g_exp_5: "自由に撮影していただいて構いません！ホストに記念撮影をお願いしてみましょう。ただし、美術館内部や特定の店舗など撮影が制限されている場所ではホストの案内に従い、他人の肖像権には配慮をお願いします。",
    q_g_exp_6: "高齢者や子供も参加できますか？",
    a_g_exp_6: "はい、老若男女どなたでも歓迎します。ただし、たくさん歩くツアーやお酒を飲むツアーの場合は制限がある場合があります。同伴者がいる場合はホストに事前にメッセージを送ってください。歩きやすいコースに調整したり、お子様への配慮を準備できます。",
    q_g_exp_7: "ツアー中のトイレや休憩は？",
    a_g_exp_7: "Locallyのツアーはパッケージ旅行のように厳しくありません。歩いていて疲れたりトイレに行きたくなったら、いつでもホストに伝えてください。現地の人だけが知る清潔なトイレの場所や、雰囲気の良いベンチで一休みできます。",
    
    // キャンセル・返金
    q_g_cancel_1: "ツアー当日に遅刻した場合は？",
    a_g_cancel_1: "ツアーは定刻に出発するため、遅刻された場合は参加が難しい場合があります。（当日キャンセル/返金不可）約束の時間の10分前には到着することをお勧めします。遅れそうな場合は必ずホストに連絡してください。",
    q_g_cancel_2: "雨天時のツアーはどうなりますか？",
    a_g_cancel_2: "小雨の場合はロマンチックな雨中ツアーとして進行します。しかし、台風など安全が懸念される悪天候時はホストの判断で中止になる場合があり、その際は手数料なしで100%全額返金されます。",
    q_g_cancel_3: "返金規定を教えてください。",
    a_g_cancel_3: "ツアー日の20日前まで100%、7日前まで70%、1日前まで40%返金され、当日キャンセルは返金不可です。ホスト都合によるキャンセルの場合は時期に関係なく全額返金されます。",
    q_g_cancel_4: "予約をキャンセルするといつ返金されますか？",
    a_g_cancel_4: "キャンセル申請後、システムでの処理が完了すると直ちにカード会社へキャンセル要請が送信されます。カード会社により3〜5営業日程度かかる場合があります。チェックカードの場合は通常2日以内に入金されます。",
    q_g_cancel_5: "日程変更は可能ですか？",
    a_g_cancel_5: "予約確定後の日程変更は原則不可であり、既存の予約をキャンセルして再予約する必要があります。この場合、既存予約のキャンセル時点に応じたキャンセル料が発生する可能性がありますのでご注意ください。",

    // アカウント管理
    q_g_account_1: "ホストは信頼できる人ですか？",
    a_g_account_1: "Locallyのすべてのホストは厳格な本人確認（身分証、電話番号認証、口座認証）を経て登録されています。また、実際にツアーに参加したゲストの正直なレビューにより評判が透明に管理されているため、安心してご利用いただけます。",
    q_g_account_2: "パスワードを忘れました。",
    a_g_account_2: "ログイン画面下部の「パスワードをお忘れの方」をクリックし、メール認証後に再設定できます。",
    q_g_account_3: "退会するにはどうすればよいですか？",
    a_g_account_3: "マイページ > アカウント設定の下部から退会可能です。退会時、すべての旅行記録とクーポンは消滅し、復元できません。",

    // [FAQ Items - Host]
    // ホスト開始
    q_h_start_1: "ホストの登録条件はありますか？",
    a_h_start_1: "資格は必要ありません！現地に住んでいて、自分の好みや物語を共有したい方なら誰でも歓迎です。グルメツアー、散歩、ショッピングなど、あなたの日常が誰かにとっては特別な旅行になります。",
    q_h_start_2: "登録費用はかかりますか？",
    a_h_start_2: "いいえ、ホスト登録およびツアー商品登録は全額無料です。予約が確定して収益が発生した時のみ、所定の手数料が発生します。",
    q_h_start_3: "手数料はいくらですか？",
    a_h_start_3: "Locallyのプラットフォーム手数料は予約金額の20%です。この手数料には決済代行手数料、サーバー維持費、マーケティング費用、税金、付加費用などが含まれています。",
    q_h_start_4: "収益はどれくらいになりますか？",
    a_h_start_4: "ツアー料金はホスト様が直接設定します。人気ホストの場合、月数百万ウォンの副収入を得ることもあります。Locally手数料(20%)を除いた金額が精算されます。",
    q_h_start_5: "外国語が上手でなければなりませんか？",
    a_h_start_5: "外国人向けツアーなら必須ですが、韓国人旅行者のみを対象とするなら韓国語だけでも十分です。語学力より親切さと現地の知識が重要です。",
    q_h_start_6: "どんなツアーを作れますか？",
    a_h_start_6: "グルメツアー、路地裏散歩、登山、料理教室、写真撮影など、現地でできるすべてのアクティビティが可能です。大それたものでなくても構いません。現地の人だけが知る「リアル」な体験を共有してください。",
    q_h_start_7: "プロフィール写真は必ず本人でなければなりませんか？",
    a_h_start_7: "はい、ゲストに信頼を与えるために、ご本人の顔がよく見える写真を推奨します。風景や動物の写真よりも、ホスト様の明るい笑顔が写った写真が予約率を高めるのに役立ちます。",
    q_h_start_8: "精算はいつされますか？",
    a_h_start_8: "ツアーが完了した日付を基準に、4週間後に登録された口座へ一括入金されます。（祝日の場合は翌営業日支給）",
    q_h_start_9: "海外在住者も登録可能ですか？",
    a_h_start_9: "はい、世界中どこでもLocallyホストとして活動できます。海外口座で精算を受ける場合、PayPal、Line Pay、またはWiseとの連携が必要になる場合があります。",

    // 運営ノウハウ
    q_h_oper_1: "スケジュール管理はどうすればいいですか？",
    a_h_oper_1: "ホストダッシュボードで可能な日付と時間だけを開けておけばOKです。本業が忙しい時はいつでも予約をブロックできるため、柔軟な活動が可能です。",
    q_h_oper_2: "最小催行人数はどう設定しますか？",
    a_h_oper_2: "商品登録時に「1人出発確定金額」を設定することができます。",
    q_h_oper_3: "ゲストへの連絡方法は？",
    a_h_oper_3: "個人の連絡先を公開することなく、Locallyアプリ内の「1:1メッセージ」機能を通じて安全にやり取りします。予約確定前でも問い合わせメッセージを受け取ることができます。",
    q_h_oper_4: "ノーショー(No-Show)が発生したら？",
    a_h_oper_4: "心配しないでください。予約確定時に決済が完了しているため、ゲストが現れなくても規定に従って精算金を受け取ることができます。",
    q_h_oper_5: "迷惑なゲストにはどう対処しますか？",
    a_h_oper_5: "ツアー進行中に無礼な態度や安全を脅かす行動をするゲストがいれば、直ちにLocallyカスタマーセンターに通報してください。事実確認後、該当ゲストの利用制限措置を取り、ホスト様を保護するために最善を尽くします。",
    // [Reservation - Add]
    res_empty_title: "予約履歴がありません。",
    res_empty_upcoming: "体験を登録して、最初のゲストを迎えましょう！",
    res_empty_cancelled: "キャンセルされた予約はありません。（良い知らせですね！）",
    res_empty_date: "この期間の予約履歴はありません。",
    res_toast_new: "🎉 新しい予約が入りました！",
    res_toast_cancel: "🚨 予約キャンセルリクエストが届きました。",
    res_error_load: "予約情報の読み込みに失敗しました。",
    res_cancel_confirm_msg: "「OK」を押すとチャットルームに移動します。",
    res_cancel_ask: "ゲストに直接キャンセルを依頼しますか？",
    res_refund_confirm_prefix: "'",
    res_refund_confirm_suffix: "' 様のキャンセルを承認して返金しますか？",
    res_toast_approved: "キャンセルが承認されました。"
  },

  // 🟢 중국어 (Chinese)
  zh: {
    host_mode: "切换房东模式",
    guest_mode: "切换游客模式",
    become_host: "成为房东",
    login: "登录",
    logout: "退出",
    signup: "注册",
    messages: "消息",
    notifications: "通知",
    cat_exp: "体验",
    cat_service: "服务",
    city_all: "全部",
    city_tokyo: "东京",
    city_osaka: "大阪",
    city_fukuoka: "福冈",
    city_sapporo: "札幌",
    city_nagoya: "名古屋",
    city_seoul: "首尔",
    city_busan: "釜山",
    city_jeju: "济州",
    footer_support: "支持",
    footer_intro: "关于 Locally",
    footer_notice: "公告",
    footer_help: "帮助中心",
    footer_admin: "管理员",
    footer_hosting: "出租",
    footer_become_host: "成为房东",
    footer_community: "社区论坛",
    footer_locally: "Locally",
    footer_news: "新闻",
    footer_careers: "招聘信息",
    footer_investors: "投资者",
    footer_partnership: "合作咨询",
    footer_social: "社交媒体",
    footer_privacy: "隐私政策",
    footer_terms: "服务条款",
    footer_travel_terms: "旅游条款",
    footer_refund: "退款政策",
    footer_sitemap: "网站地图",
    copyright: "© 2026 Locally, Inc.",
    my_trips: "行程",
    wishlist: "心愿单",
    wishlist_empty: "还没有收藏的体验",
    wishlist_desc: "找到喜欢的体验并点击爱心！",
    explore_exp: "浏览体验",
    trip_upcoming: "即将开始",
    trip_past: "过去的行程",
    trip_review: "写评价",
    trip_pay_date: "支付时间",
    trip_map: "地图",
    receipt: "收据",
    paid_label: "支付:",
    trip_add_calendar: "添加到日历",
    trip_view_again: "查看体验",
    trip_cancel_req: "申请取消",
    trip_start_in: "天后出发",
    month_1: "1月", month_2: "2月", month_3: "3月", month_4: "4月", month_5: "5月", month_6: "6月",
    month_7: "7月", month_8: "8月", month_9: "9月", month_10: "10月", month_11: "11月", month_12: "12月",
    day_0: "日", day_1: "一", day_2: "二", day_3: "三", day_4: "四", day_5: "五", day_6: "六",
    select_year: "选择年份",
    confirm_date: "确认",
    per_person: "/ 人",
    // 👇 여기 추가
    error_prefix: "错误:",
    trip_empty_title: "没有即将到来的行程",
    trip_past_empty: "没有过去的行程记录。",
    account: "账号",
    account_title: "账号与个人资料",
    account_desc: "管理您的信息并设置公开资料。",
    identity_verified: "身份已验证",
    review_from_host: "房东的评价",
    label_name: "姓名 (实名)",
    label_nationality: "国籍",
    select_nationality: "选择国籍",
    label_birth: "出生日期",
    label_gender: "性别",
    gender_male: "男",
    gender_female: "女",
    gender_other: "其他",
    label_phone: "电话号码",
    label_kakao: "KakaoTalk ID",
    label_mbti: "MBTI",
    label_email: "电子邮箱",
    label_bio: "自我介绍",
    btn_save_changes: "保存更改",
    saving: "保存中...",
    profile_photo_change_done: "头像已更改。",
    profile_photo_fail: "上传失败:",
    profile_save_success: "个人资料已保存。",
    profile_save_fail: "保存失败，请稍后重试。",
    label_no_name: "无名氏",
    label_no_nationality: "国籍未设置",
    ph_phone: "+86 138-1234-5678",
    ph_kakao: "联系用 KakaoTalk ID",
    ph_mbti: "例如 ENFP",
    ph_bio: "向房东简单介绍一下自己（爱好、旅行风格等）",
    help_phone: "* 选择国籍时会自动输入国家代码。",
    help_email: "* 登录 ID 将被更改。",
    gender_select: "请选择",
    host_honorific: " 房东",
    msg_select: "请选择对话",
    msg_list: "消息列表",
    // 👇 여기 추가
    msg_placeholder: "输入消息...",
    msg_empty: "暂无消息。",
    msg_select_chat: "请选择对话。",
    admin_chat_title: "1:1 咨询",
    admin_name: "Locally 客服",
    host_partner: "HOST PARTNER",
    host_approved: "已批准的房东",
    menu_reservation: "预订管理",
    menu_my_exp: "体验管理",
    menu_inquiry: "咨询箱",
    menu_earnings: "收入结算",
    menu_reviews: "收到的评价",
    menu_profile: "个人资料设置",
    res_status: "预订状态",
    res_desc: "管理并准备客人的预订。",
    tab_upcoming: "即将到来",
    tab_past: "历史记录",
    tab_cancel: "取消/退款",
    res_paid_at: "支付时间",
    res_income: "预计收入",
    res_people: "人参加",
    res_cancel_req: "已申请取消",
    res_cancel_msg: "收到取消申请。",
    res_reason: "理由",
    res_approve_refund: "批准并退款",
    exp_new: "创建新体验",
    exp_selling: "销售中",
    exp_edit: "编辑",
    exp_schedule: "日程管理",
    earn_title: "房东收入",
    earn_expected: "预计结算金额",
    earn_total_count: "总预订数",
    earn_summary: "结算详情",
    earn_gross: "总销售额",
    earn_fee: "服务费",
    earn_net: "最终支付额",
    profile_public: "公开资料",
    profile_private: "隐私信息",
    profile_job: "职业",
    profile_dream: "梦想旅行地",
    profile_song: "喜欢的歌",
    profile_lang: "语言",
    profile_photo_change: "更改照片",
    private_info_warning: "个人及结算信息无法直接修改。",
    private_info_desc: "此信息仅用于验证和结算。",
    info_contact: "个人信息",
    info_bank: "结算账户",
    bank_name: "银行名称",
    bank_account: "账号",
    bank_owner: "户主",
    motivation: "申请动机",
    search: "搜索",
    filter: "筛选",
    confirm: "确认",
    cancel: "取消",
    loading: "加载中...",
    search_placeholder: "搜索目的地",
    add_dates: "添加日期",
    add_guests: "添加人数",
    login_required: "请先登录。",
    welcome_title: "欢迎来到 Locally",
    welcome_subtitle: "像当地人一样旅行的最简单方式",
    email: "邮箱",
    password: "密码",
    login_button: "登录",
    or: "或",
    continue_kakao: "Kakao 登录",
    continue_google: "Google 登录",
    no_account: "没有账号？",
    agree_terms: "继续即表示您同意服务条款和隐私政策。",
    anywhere: "任意地点",
    anytime: "任意时间",
    label_destination: "地点",
    label_date: "日期",
    label_language: "语言", // 🟢 [수정] Guest -> Language
    lang_all: "全部",
    lang_ko: "韩语",
    lang_en: "英语",
    lang_ja: "日语",
    lang_zh: "中文",
    add_language: "添加语言", // 🟢 [수정] Add guests -> Add language
    date_year: "年",
    date_month: "月",
    // [Help Center]
    help_title: "帮助中心",
    help_search_placeholder: "搜索问题...",
    tab_guest: "游客 (For Guests)",
    tab_host: "房东 (For Hosts)",
    help_bottom_title: "需要更多帮助？",
    help_bottom_desc: "找不到想要的答案？\n请直接联系 Locally 客服团队。",
    btn_chat_support: "在线咨询",
    btn_email_us: "邮件咨询",
    
    // [FAQ Categories]
    faq_cat_booking: "预订与支付",
    faq_cat_experience: "体验之旅",
    faq_cat_cancellation: "取消与退款",
    faq_cat_account: "账号管理",
    faq_cat_start: "成为房东",
    faq_cat_operation: "运营秘籍",

    // [FAQ Items - Guest]
    // 预订
    q_g_booking_1: "找不到想要的日期。",
    a_g_booking_1: "Locally 的房东并非职业导游，而是拥有本职工作的当地人，因此日程可能会有所变动。如果日历上没有您想要的日期，请点击“联系房东”发送消息！房东可能会确认日程并为您协调时间。",
    q_g_booking_2: "可以预订私人（包团）游吗？",
    a_g_booking_2: "当然可以。预订时请选择“私人游”选项。（如果没有该选项，请私信咨询房东）房东将为您准备专属的定制体验。",
    q_g_booking_3: "什么是“单人成团”选项？",
    a_g_booking_3: "通常情况下需 2 人以上方可成团，但我们为独自旅行的游客提供“单人成团”选项。支付额外费用后即可确保出发，无需担心人数不足。如果后续有其他游客加入，您支付的额外费用将全额退还。",
    q_g_booking_4: "支持哪些支付方式？",
    a_g_booking_4: "目前支持韩国国内信用卡/借记卡、KakaoPay、NaverPay 等快捷支付。海外发行的卡支持 Visa、Master 卡，后续将引入更多支付方式。",
    q_g_booking_5: "可以和同伴分开支付吗？",
    a_g_booking_5: "可以。请各自预订，并选择相同的时间段。预订后请给房东留言“我们是同行者”，以便房东提前做好准备。",
    
    // 体验
    q_g_exp_1: "不会外语可以参加吗？",
    a_g_exp_1: "别担心！您可以毫无语言障碍地愉快享受。Locally 房东与您的所有沟通都将以您的语言进行，请放心。",
    q_g_exp_2: "如何联系房东？",
    a_g_exp_2: "预订确认后，“消息”标签页中会开启与房东的 1:1 聊天室。集合地点、准备物品、时间等任何疑问都可以自由咨询。",
    q_g_exp_3: "如果在旅游当天迟到怎么办？",
    a_g_exp_3: "行程将按预定时间出发，迟到可能导致无法参加，且将被视为当日取消，无法退款。如果您可能会迟到，请务必提前联系房东。",
    q_g_exp_4: "费用包含餐费或饮料吗？",
    a_g_exp_4: "大多数行程不包含餐费。通常是在探访当地美食店时各自支付点餐费用，或者由房东先支付，行程结束后再进行结算（AA制）。预订前请务必确认“包含项目”。",
    q_g_exp_5: "可以拍照吗？",
    a_g_exp_5: "可以自由拍照！还可以请房东帮您拍人生美照。但在美术馆内部或特定商店等限制拍摄的区域，请听从房东的指引，并请注意保护他人的肖像权。",
    q_g_exp_6: "老人或孩子可以参加吗？",
    a_g_exp_6: "是的，无论男女老少都欢迎。但步行较多或涉及饮酒的行程可能会有限制。如果有同伴，请提前给房东发消息。房东可以调整为轻松的步行路线或为孩子准备特别关照。",
    q_g_exp_7: "行程中如何上洗手间或休息？",
    a_g_exp_7: "Locally 的行程不像跟团游那样紧凑。走累了或想上洗手间，随时告诉房东。房东知道当地只有当地人知道的干净洗手间位置，或者氛围很好的休息长椅。",
    
    // 取消与退款
    q_g_cancel_1: "如果当天迟到怎么办？",
    a_g_cancel_1: "行程按时出发，迟到可能无法参加。（视为当日取消/不可退款）建议提前 10 分钟到达。如果预计会迟到，请务必立即联系房东。",
    q_g_cancel_2: "下雨天行程会照常进行吗？",
    a_g_cancel_2: "小雨将作为浪漫的雨中漫步照常进行。但台风等由于恶劣天气存在安全隐患时，房东可能会决定取消，此时将免手续费 100% 全额退款。",
    q_g_cancel_3: "退款规定是怎样的？",
    a_g_cancel_3: "出发日前 20 天退 100%，7 天前退 70%，1 天前退 40%，当天取消不可退款。若因房东原因取消，无论何时均全额退款。",
    q_g_cancel_4: "取消预订后何时退款？",
    a_g_cancel_4: "取消申请经系统处理完成后，会立即向发卡行发送取消请求。根据发卡行的不同，可能需要 3~5 个工作日。借记卡通常在 2 天内入账。",
    q_g_cancel_5: "可以更改日期吗？",
    a_g_cancel_5: "预订确认后原则上不可更改日期，需取消原预订后重新预订。此时可能会根据原预订的取消时间产生退款手续费，请注意。",

    // 账号管理
    q_g_account_1: "房东值得信任吗？",
    a_g_account_1: "Locally 的所有房东都经过严格的身份认证（本人确认、手机号认证、账户认证）。此外，通过实际参与行程的游客的真实评价，透明地管理声誉，请放心预订。",
    q_g_account_2: "忘记了密码。",
    a_g_account_2: "点击登录屏幕下方的“找回密码”，通过邮箱验证后即可重新设置。",
    q_g_account_3: "如何注销会员？",
    a_g_account_3: "可在 我的页面 > 账号设置 底部进行注销。注销时所有旅行记录和优惠券将消失，且无法恢复。",

    // [FAQ Items - Host]
    // 成为房东
    q_h_start_1: "注册房东有什么条件？",
    a_h_start_1: "无需资格证！只要居住在当地，愿意分享自己的喜好和故事，任何人都欢迎。探店、散步、购物等，您的日常生活对别人来说可能就是一次特别的旅行。",
    q_h_start_2: "需要注册费吗？",
    a_h_start_2: "不需要，注册房东及发布行程全额免费。只有预订确认产生收益时，才会收取规定的手续费。",
    q_h_start_3: "手续费是多少？",
    a_h_start_3: "Locally 的平台手续费为预订金额的 20%。该费用包含支付代理费、服务器维护费、营销费、税金及附加费用等。",
    q_h_start_4: "收益有多少？",
    a_h_start_4: "行程费用由房东亲自设定。人气房东每月可获得数百万韩元的副业收入。扣除 Locally 手续费 (20%) 后的金额将进行结算。",
    q_h_start_5: "必须精通外语吗？",
    a_h_start_5: "如果是针对外国游客的行程，必须会外语；但如果是针对韩国游客，只会韩语也足够。相比语言能力，亲切感和当地知识更重要。",
    q_h_start_6: "可以制作什么样的行程？",
    a_h_start_6: "探店、胡同散步、登山、烹饪课、摄影等，所有在当地能进行的活动都可以。不需要很宏大。请分享只有当地人知道的“真实”体验。",
    q_h_start_7: "头像必须是本人吗？",
    a_h_start_7: "是的，为了给游客信任感，建议使用能看清面部的本人照片。相比风景或动物照片，房东灿烂的笑容有助于提高预订率。",
    q_h_start_8: "什么时候结算？",
    a_h_start_8: "以行程完成日期为准，4 周后统一汇入您注册的账户。（如遇节假日，则顺延至下一个工作日发放）",
    q_h_start_9: "居住在海外也可以注册吗？",
    a_h_start_9: "是的，无论身在世界何处，都可以作为 Locally 房东开展活动。如需通过海外账户接收结算，可能需要关联 PayPal、Line Pay 或 Wise。",

    // 运营秘籍
    q_h_oper_1: "如何管理日程？",
    a_h_oper_1: "在房东仪表板中，只需开启可用的日期和时间即可。本职工作忙碌时，可以随时屏蔽预订，活动非常灵活。",
    q_h_oper_2: "如何设定最少出发人数？",
    a_h_oper_2: "发布商品时可以设定“单人成团金额”。",
    q_h_oper_3: "如何联系游客？",
    a_h_oper_3: "无需通过个人联系方式，通过 Locally App 内的“1:1 消息”功能安全沟通。预订确认前也能收到咨询消息。",
    q_h_oper_4: "如果游客未出现(No-Show)怎么办？",
    a_h_oper_4: "别担心。预订确认时已完成支付，即使游客未出现，也会按照规定向您支付结算金。",
    q_h_oper_5: "如何应对无理取闹的游客？",
    a_h_oper_5: "如果行程中遇到无礼或威胁安全的游客，请立即向 Locally 客服中心举报。确认事实后，我们将采取限制该游客使用的措施，尽全力保护房东。",
    // [Reservation - Add]
    res_empty_title: "暂无预订记录。",
    res_empty_upcoming: "发布体验，迎接您的第一位房客吧！",
    res_empty_cancelled: "没有取消的预订。（这是个好消息！）",
    res_empty_date: "该期间无预订记录。",
    res_toast_new: "🎉 收到新的预订！",
    res_toast_cancel: "🚨 收到取消预订请求。",
    res_error_load: "加载预订信息失败。",
    res_cancel_confirm_msg: "点击“确定”进入聊天室。",
    res_cancel_ask: "要求房客直接取消吗？",
    res_refund_confirm_prefix: "批准 '",
    res_refund_confirm_suffix: "' 的取消并退款吗？",
    res_toast_approved: "取消已批准。"
  }
};

const LanguageContext = createContext<any>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Locale>('ko');

  useEffect(() => {
    const saved = localStorage.getItem('app_lang') as Locale;
    if (saved && dictionary[saved]) setLang(saved);
  }, []);

  const changeLang = (newLang: Locale) => {
    setLang(newLang);
    localStorage.setItem('app_lang', newLang);
  };

  const t = (key: string) => {
    return dictionary[lang]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang: changeLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);