import assert from 'node:assert/strict';
import {test} from 'node:test';
import {hostProfileDigest,selectHostProfileSources,planHostProfileMigration,validateHostProfilePlan,executeHostProfilePlan} from './host-profile-media-migration.mjs';
import {hostProfileOperatorBinding} from './host-profile-media-operator.mjs';
const owner='11111111-1111-4111-8111-111111111111',id='22222222-2222-4222-8222-222222222222',key='profile/'+owner+'_1',oldUrl='https://uhinvcydgzqlpnvieyal.supabase.co/storage/v1/object/public/images/'+key,bytes=new Uint8Array([255,216,255,1]);
function fixture(){return {bucketPublic:true,legacyWritesFrozen:true,objects:[{key,owner,size:4,mime:'image/jpeg',version:'fixture',updatedAt:'fixture'},{key:'profile/'+owner+'_2',owner,size:3,mime:'image/heic',version:'orphan'}],references:[{kind:'host_application',id,owner,locator:oldUrl},{kind:'profile_legacy_host',id:owner,owner,locator:oldUrl},{kind:'auth_legacy_host',id:owner,owner,locator:oldUrl,metadataDigest:'a'.repeat(64)},{kind:'profile_legacy_host',id:'33333333-3333-4333-8333-333333333333',owner:'33333333-3333-4333-8333-333333333333',locator:'https://uhinvcydgzqlpnvieyal.supabase.co/storage/v1/object/public/images/community/outside-scope'}]};}
const plan=i=>planHostProfileMigration(i,async()=>bytes,(_b,m)=>m);
function deps(inv){const calls=[];return {calls,inventory:async()=>structuredClone(inv),readSource:async()=>bytes,validateImage:(_b,m)=>m,prepare:async(item)=>{calls.push('prepare');return {id:item.assetId,public_url:item.newUrl};},cas:async(item,rollback)=>{calls.push(rollback?'rollback':'apply');for(const r of inv.references.filter(r=>item.references.some(p=>p.kind===r.kind&&p.id===r.id)))r.locator=rollback?item.oldUrl:item.newUrl;},verifyCommitted:async()=>calls.push('verify-commit'),verifyRollback:async()=>calls.push('verify-rollback'),record:async()=>calls.push('record')};}
test('fresh live set includes Auth/shared references; LEGACY_HOST_UNREFERENCED_RETAINED excludes HEIC orphan',async()=>{const i=fixture(),s=selectHostProfileSources(i);assert.equal(s.entries.length,1);assert.equal(s.entries[0].references.length,3);assert.equal(s.unreferenced,1);const p=await plan(i);assert.equal(p.entries.length,1);assert.equal(p.legacy_unreferenced_retained,1);validateHostProfilePlan(p,p.planDigest);assert.deepEqual(await plan(i),p);});
test('owner, missing byte/object, private bucket, aliases and Auth/public disagreements block',async()=>{for(const mutate of [i=>i.bucketPublic=false,i=>i.objects.shift(),i=>i.objects[0].owner=id,i=>i.references[0].locator+='?private=capability',i=>i.references[1].locator='https://external.example/new',i=>i.references[2].metadataDigest='invalid',i=>i.references.push({...i.references[0]})]){const i=fixture();mutate(i);assert.throws(()=>selectHostProfileSources(i));}await assert.rejects(planHostProfileMigration(fixture(),async()=>new Uint8Array(2),(_b,m)=>m));});
test('digest and immutable identity protect approved scope before any provider call',async()=>{const p=await plan(fixture());for(const mutate of [p=>p.entries[0].bucket='locally-public-avatars',p=>p.entries[0].references[0].kind='oauth',p=>p.entries[0].ownerId=id]){const b=structuredClone(p);mutate(b);const payload={...b};delete payload.planDigest;b.planDigest=hostProfileDigest(payload);assert.throws(()=>validateHostProfilePlan(b,b.planDigest));}const d=deps(fixture(),p);await assert.rejects(executeHostProfilePlan(p,'0'.repeat(64),d,'apply'));assert.deepEqual(d.calls,[]);});
test('prepare, apply, verified resume, safe rollback are group atomic and have zero deletes',async()=>{const i=fixture(),p=await plan(i),d=deps(i,p);assert.equal((await executeHostProfilePlan(p,p.planDigest,d,'prepare')).applied,0);assert.equal((await executeHostProfilePlan(p,p.planDigest,d,'apply')).applied,1);assert.equal((await executeHostProfilePlan(p,p.planDigest,d,'apply')).resumed,1);const r=await executeHostProfilePlan(p,p.planDigest,d,'rollback');assert.equal(r.rolledBack,1);assert.equal(r.physicalDeletes,0);assert.equal(r.sourceWrites,0);assert(i.references.filter(r=>r.kind!=='profile_legacy_host'||r.id===owner).every(r=>r.locator===oldUrl));});
test('newer Auth metadata/locator, source metadata/bytes or newly shared reference cannot be overwritten',async()=>{const p=await plan(fixture());for(const mutate of [i=>i.references[0].locator='https://external.example/newer',i=>i.references[2].metadataDigest='b'.repeat(64),i=>i.objects[0].version='new',i=>i.references.push({kind:'host_application',id:owner,owner,locator:oldUrl})]){const i=fixture();mutate(i);const d=deps(i,p);await assert.rejects(executeHostProfilePlan(p,p.planDigest,d,'apply'));assert.deepEqual(d.calls,[]);}const d=deps(fixture(),p);d.readSource=async()=>new Uint8Array([255,216,255,9]);await assert.rejects(executeHostProfilePlan(p,p.planDigest,d,'apply'));assert.deepEqual(d.calls,[]);});
test('actual S3 wrapper is bucket-locked create-only, rejects namespace/permission expansion, never has delete',async()=>{const calls=[];const binding=hostProfileOperatorBinding({R2_ENDPOINT:'https://'+'a'.repeat(32)+'.r2.cloudflarestorage.com',HOST_PROFILE_R2_ACCESS_KEY_ID:'fixture-only',HOST_PROFILE_R2_SECRET_ACCESS_KEY:'fixture-only'},async request=>{calls.push(request);return new Response(null,{status:412});});assert(!('delete' in binding));await assert.rejects(binding.head('avatars/v1/arbitrary'));const p=await plan(fixture()),key=p.entries[0].key;await assert.rejects(binding.put(key,bytes,{onlyIf:{},httpMetadata:{},customMetadata:{}}));await binding.put(key,bytes,{onlyIf:{etagDoesNotMatch:'*'},sha256:p.entries[0].sha256,httpMetadata:{contentType:'image/jpeg',cacheControl:'immutable'},customMetadata:{}});assert.equal(calls.length,1);assert.equal(calls[0].method,'PUT');assert.equal(calls[0].headers.get('if-none-match'),'*');assert(calls[0].url.includes('/locally-public-host-profile-originals/'));});
import {prepareHostProfileCutoverConfig} from './prepare-host-profile-cutover-config.mjs';
test('release overlay requires completed Avatar true and changes only Host binding/flag, queues/crons/services/DO unchanged',()=>{const base={keep_vars:true,env:{production:{name:'locally-web-opennext-production',vars:{AVATAR_R2_SOURCE_ENABLED:'true'},r2_buckets:[{binding:'PUBLIC_AVATAR_R2',bucket_name:'locally-public-avatars'}],queues:{consumers:[{queue:'source'},{queue:'translation'}]},triggers:{crons:['one','two','three','four','five']},services:[{binding:'service'}],durable_objects:{bindings:[{name:'bridge'}]}}}};const next=prepareHostProfileCutoverConfig(base,'true');assert.equal(next.env.production.vars.AVATAR_R2_SOURCE_ENABLED,'true');assert.deepEqual(next.env.production.queues,base.env.production.queues);assert.deepEqual(next.env.production.triggers,base.env.production.triggers);assert.deepEqual(next.env.production.services,base.env.production.services);assert.deepEqual(next.env.production.durable_objects,base.env.production.durable_objects);assert.throws(()=>prepareHostProfileCutoverConfig({...base,keep_vars:false}));assert.throws(()=>prepareHostProfileCutoverConfig({keep_vars:true,env:{production:{...base.env.production,vars:{AVATAR_R2_SOURCE_ENABLED:'false'}}}}));});

test('legacy freeze is a mandatory apply gate, not a read-only plan restriction',async()=>{const i=fixture();i.legacyWritesFrozen=false;const p=await plan(i),d=deps(i);await assert.rejects(executeHostProfilePlan(p,p.planDigest,d,'apply'),/legacy_writer_not_frozen/);assert.deepEqual(d.calls,[]);});
import {assertConfigUnchanged} from './candidate-release-contract.mjs';
test('existing candidate integrity gate still rejects Host binding/flag drift; explicit bootstrap must precede a new baseline',()=>{const before={routes:[],customDomains:[],subdomain:{enabled:false,previews_enabled:false},crons:['one','two','three','four','five'],queueConsumers:[],bindings:[{name:'PUBLIC_AVATAR_R2',type:'r2_bucket',bucket_name:'locally-public-avatars'}]};const after=structuredClone(before);after.bindings.push({name:'PUBLIC_HOST_PROFILE_SOURCE_R2',type:'r2_bucket',bucket_name:'locally-public-host-profile-originals'});assert.throws(()=>assertConfigUnchanged(before,after),e=>e.code==='candidate_binding_or_secret_drift');assertConfigUnchanged(after,structuredClone(after));});

test('Host operator credential cannot reuse known Avatar/Experience/derivative/destination/Host reader authority',()=>{const base={R2_ENDPOINT:'https://'+'a'.repeat(32)+'.r2.cloudflarestorage.com',HOST_PROFILE_R2_ACCESS_KEY_ID:'synthetic-host-id',HOST_PROFILE_R2_SECRET_ACCESS_KEY:'fixture'};for(const name of ['AVATAR_R2_ACCESS_KEY_ID','R2_AVATAR_SOURCE_READ_ACCESS_KEY_ID','R2_SOURCE_ACCESS_KEY_ID','R2_ACCESS_KEY_ID','AWS_ACCESS_KEY_ID','R2_HOST_PROFILE_SOURCE_READ_ACCESS_KEY_ID'])assert.throws(()=>hostProfileOperatorBinding({...base,[name]:base.HOST_PROFILE_R2_ACCESS_KEY_ID}),/credential_reused/);});
