import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {verifyReadOnlyClientInteraction} from '../../scripts/cloudflare/run-candidate-browser-smoke.mjs';
export function createRscFixture({context,origin,versionId,record=()=>{},screenshotPath}){
 const rows=[],requests=new WeakMap(),proofs=new WeakMap(),jobs=new Set();let seq=0;
 context.on('request',q=>{const u=new URL(q.url());if(u.origin!==origin||!['fetch','xhr'].includes(q.resourceType())||u.pathname.startsWith('/api/'))return;
  const h=q.headers();if(h.rsc!=='1')return;const row={id:'rsc'+(++seq),pathname:u.pathname,startTimestamp:new Date().toISOString(),started:performance.now(),method:q.method(),resourceType:q.resourceType(),rscHeader:true,prefetch:h['next-router-prefetch']==='1',treeHeaderPresent:Boolean(h['next-router-state-tree']),queryKeys:[...u.searchParams.keys()].sort(),targetVersion:versionId};requests.set(q,row);rows.push(row);record('rsc-start',{id:row.id,pathname:row.pathname,prefetch:row.prefetch})});
 context.on('response',r=>{const q=r.request(),row=requests.get(q);if(!row)return;const task=(async()=>{row.status=r.status();row.responseMs=Math.round(performance.now()-row.started);row.contentType=await r.headerValue('content-type');const failure=await r.finished();assert.equal(failure,null);const b=await r.body();row.bodyBytes=b.length;row.bodySha256=createHash('sha256').update(b).digest('hex');row.bodyComplete=true;row.finishedMs=Math.round(performance.now()-row.started);const p=proofs.get(q);row.overrideApplied=p?.anonymous===true&&p.forwarding==='stateless-read';row.statelessAnonymous=p?.anonymous===true;row.verdict=row.status===200&&row.contentType?.includes('text/x-component')&&b.length>0&&row.overrideApplied?'PASS':'FAIL';record('rsc-complete',{id:row.id,pathname:row.pathname,status:row.status,bytes:row.bodyBytes,verdict:row.verdict});})().catch(e=>{row.verdict='FAIL';row.errorName=e.name});jobs.add(task);task.finally(()=>jobs.delete(task))});
 context.on('requestfailed',q=>{const row=requests.get(q);if(row){row.failure=q.failure()?.errorText;row.failureMs=Math.round(performance.now()-row.started)}});
 const verifyInteraction=async page=>{const receipt=await verifyReadOnlyClientInteraction(page);if(receipt.pathname!=='/')return receipt;
  const link=page.locator('a[href^="/experiences/"]:visible').first();await link.waitFor({state:'visible',timeout:15000});const href=await link.getAttribute('href');assert(/^\/experiences\/\d+$/.test(href));
  record('ui-link-click',{pathname:href,selector:'existing visible Next Link experience card'});
  await link.click({timeout:15000});await page.waitForURL(u=>u.pathname===href,{timeout:30000});await page.locator('h1:visible').first().waitFor({state:'visible',timeout:15000});
  // Only await the response generated by the real UI. No synthetic fetch and no
  // coverage assignment. The unchanged gate independently observes this 200.
  const deadline=performance.now()+15000;while(!rows.some(r=>r.pathname===href&&r.verdict==='PASS')){assert(performance.now()<deadline,'Real UI RSC body completion was not observed');await new Promise(resolve=>setTimeout(resolve,50));}
  assert(!rows.some(r=>r.verdict==='FAIL'),'RSC capture/body/identity failed');
  await page.screenshot({path:screenshotPath});
  await page.goBack({waitUntil:'domcontentloaded',timeout:30000});await page.waitForURL(u=>u.pathname==='/',{timeout:30000});await page.locator('a[href^="/experiences/"]:visible').first().waitFor({state:'visible',timeout:15000});record('ui-link-return-home',{pathname:'/'});return receipt;
 };
 return{verifyInteraction,onApplied:(p,q)=>{if(q)proofs.set(q,p)},rows,finish:async()=>{await Promise.all([...jobs]);return rows.map(row=>{const r={...row};delete r.started;return r})}};
}
