import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import { PGlite } from '@electric-sql/pglite';

const migration = readFileSync('supabase/migrations/20261001170718_admin_message_monitoring_phase_1.sql', 'utf8');
const guest = '11111111-1111-4111-8111-111111111111';
const host = '22222222-2222-4222-8222-222222222222';
const admin = '33333333-3333-4333-8333-333333333333';
const whitelist = '44444444-4444-4444-8444-444444444444';
const outsider = '55555555-5555-4555-8555-555555555555';

async function fixture() {
  const db = new PGlite();
  await db.exec(`
    CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role BYPASSRLS;
    CREATE SCHEMA auth; CREATE SCHEMA private;
    CREATE TABLE auth.users (id uuid PRIMARY KEY, email text);
    CREATE TABLE public.users (id uuid PRIMARY KEY, role text);
    CREATE TABLE public.admin_whitelist (id bigint, email text);
    CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$ SELECT nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
    CREATE FUNCTION private.is_admin_reader() RETURNS boolean LANGUAGE sql SECURITY DEFINER AS $$ SELECT EXISTS(SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin') $$;
    CREATE TABLE public.inquiries (id bigint PRIMARY KEY, user_id uuid, host_id uuid, type text, status text, content text, updated_at timestamptz DEFAULT now());
    CREATE TABLE public.inquiry_messages (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, inquiry_id bigint REFERENCES public.inquiries(id), sender_id uuid, content text, type text DEFAULT 'text', is_read boolean DEFAULT false, read_at timestamptz, created_at timestamptz DEFAULT now());
    ALTER TABLE public.inquiries ENABLE ROW LEVEL SECURITY;
    ALTER TABLE public.inquiry_messages ENABLE ROW LEVEL SECURITY;
    CREATE POLICY participant_read ON public.inquiries FOR SELECT TO authenticated USING (auth.uid() IN (user_id, host_id));
    CREATE POLICY admin_read ON public.inquiries FOR SELECT TO authenticated USING (private.is_admin_reader());
    CREATE POLICY participant_messages ON public.inquiry_messages FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.inquiries i WHERE i.id = inquiry_id));
    CREATE POLICY "Users can update own inquiries" ON public.inquiries FOR UPDATE USING (auth.uid() IN (user_id, host_id));
    CREATE POLICY "Users can update messages in their inquiries" ON public.inquiry_messages FOR UPDATE USING (EXISTS (SELECT 1 FROM public.inquiries i WHERE i.id = inquiry_id AND auth.uid() IN (i.user_id, i.host_id)));
    GRANT USAGE ON SCHEMA public, auth, private TO anon, authenticated, service_role;
    GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
    GRANT UPDATE (content, sender_id, type, is_read, read_at) ON public.inquiry_messages TO authenticated;
    GRANT UPDATE (user_id, host_id, type, status) ON public.inquiries TO authenticated;
    GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO service_role;
    INSERT INTO public.users VALUES ('${guest}', 'guest'), ('${host}', 'host'), ('${admin}', 'admin'), ('${whitelist}', 'guest'), ('${outsider}', 'guest');
    INSERT INTO auth.users VALUES ('${whitelist}', 'staff@example.invalid'), ('${guest}', 'guest@example.invalid');
    INSERT INTO public.admin_whitelist VALUES (1, 'staff@example.invalid');
    INSERT INTO public.inquiries VALUES (1, '${guest}', '${host}', 'general', 'open', 'preview', '2026-10-01T01:00Z'), (2, '${guest}', null, 'admin_support', 'resolved', 'done', '2026-10-01T01:00Z'), (3, '${admin}', '${guest}', 'admin', 'resolved', 'legacy', '2026-10-01T01:00Z');
    INSERT INTO public.inquiry_messages (inquiry_id, sender_id, content) VALUES (1, '${host}', 'host message');
  `);
  return db;
}

async function as(db, role, actor, sql, params = []) {
  await db.exec(`SET ROLE ${role}; SET request.jwt.claim.sub = '${actor}';`);
  try { return await db.query(sql, params); } finally { await db.exec('RESET ROLE'); }
}

test('migration removes table and column write grants while retaining Guest/Host/Admin RLS reads and server send/read', async () => {
  const db = await fixture();
  try {
    await as(db, 'authenticated', guest, "UPDATE public.inquiry_messages SET content = 'tampered' WHERE id = 1");
    assert.equal((await db.query('SELECT content FROM inquiry_messages WHERE id=1')).rows[0].content, 'tampered', 'reproduces the old vulnerability');
    await db.exec(migration);
    await db.exec(migration); // safe rerun, no duplicate triggers/functions
    for (const role of ['anon', 'authenticated']) {
      for (const table of ['inquiries', 'inquiry_messages']) {
        const grants = (await db.query(`SELECT has_table_privilege($1,$2,'UPDATE') AS table_update, has_any_column_privilege($1,$2,'UPDATE') AS column_update`, [role, table])).rows[0];
        assert.deepEqual(grants, { table_update: false, column_update: false });
      }
      for (const actor of [guest, host]) {
        for (const sql of [
          "UPDATE inquiry_messages SET content='changed' WHERE id=1",
          `UPDATE inquiry_messages SET sender_id='${guest}', type='deleted' WHERE id=1`,
          "UPDATE inquiry_messages SET is_read=true, read_at=now() WHERE id=1",
          `UPDATE inquiries SET user_id='${outsider}', host_id='${guest}', type='admin', status='resolved' WHERE id=1`,
          `INSERT INTO inquiry_messages(inquiry_id,sender_id,content) VALUES(1,'${guest}','forged')`,
          'DELETE FROM inquiry_messages WHERE id=1',
        ]) await assert.rejects(as(db, role, actor, sql), /permission denied/);
      }
    }
    for (const actor of [guest, host]) assert.ok((await as(db, 'authenticated', actor, 'SELECT id FROM inquiries WHERE id=1')).rows.length);
    assert.equal((await as(db, 'authenticated', outsider, 'SELECT * FROM inquiry_messages')).rows.length, 0);
    assert.equal((await as(db, 'authenticated', admin, 'SELECT id FROM inquiries')).rows.length, 3);
    await as(db, 'service_role', guest, `INSERT INTO inquiry_messages(inquiry_id,sender_id,content) VALUES(1,'${guest}','normal send')`);
    await as(db, 'service_role', host, `UPDATE inquiry_messages SET is_read=true,read_at=now() WHERE inquiry_id=1 AND sender_id<>'${host}'`);
    assert.equal((await db.query("SELECT is_read FROM inquiry_messages WHERE content='normal send'")).rows[0].is_read, true);
    for (const fn of ['get_admin_inquiry_activity(bigint[])', 'ack_admin_inquiry_messages(bigint,bigint)']) {
      for (const role of ['anon', 'authenticated', 'service_role']) {
        assert.equal((await db.query('SELECT has_function_privilege($1,$2,\'EXECUTE\') AS allowed', [role, `public.${fn}`])).rows[0].allowed, role === 'service_role');
      }
    }
  } finally { await db.close(); }
});

test('customer reinquiry reopens resolved support, including legacy ownership; admin/whitelist replies never reopen', async () => {
  const db = await fixture();
  try {
    await db.exec(migration);
    for (const staff of [admin, whitelist]) {
      await as(db, 'service_role', staff, `INSERT INTO inquiry_messages(inquiry_id,sender_id,content) VALUES(2,'${staff}','staff reply')`);
      assert.equal((await db.query('SELECT status FROM inquiries WHERE id=2')).rows[0].status, 'resolved');
    }
    for (const id of [2, 3]) {
      const before = (await db.query('SELECT updated_at FROM inquiries WHERE id=$1', [id])).rows[0].updated_at;
      await as(db, 'service_role', guest, `INSERT INTO inquiry_messages(inquiry_id,sender_id,content) VALUES($1,'${guest}','follow-up')`, [id]);
      const row = (await db.query('SELECT status, support_reopened_at, updated_at FROM inquiries WHERE id=$1', [id])).rows[0];
      assert.equal(row.status, 'open'); assert.ok(row.support_reopened_at); assert.ok(row.updated_at > before);
      const staleClose = await db.query("UPDATE inquiries SET status='resolved' WHERE id=$1 AND updated_at=$2 RETURNING id", [id, before]);
      assert.equal(staleClose.rows.length, 0, 'stale close loses to the customer insert');
      // A stale application preview timestamp cannot restore the old CAS version.
      await db.query('UPDATE inquiries SET content=$1,updated_at=$2 WHERE id=$3', ['preview', before, id]);
      assert.ok((await db.query('SELECT updated_at FROM inquiries WHERE id=$1', [id])).rows[0].updated_at > row.updated_at);
      await db.query("UPDATE inquiries SET status='resolved' WHERE id=$1", [id]);
      assert.equal((await db.query('SELECT support_reopened_at FROM inquiries WHERE id=$1', [id])).rows[0].support_reopened_at, null);
      await as(db, 'service_role', guest, `INSERT INTO inquiry_messages(inquiry_id,sender_id,content) VALUES($1,'${guest}','after close')`, [id]);
      assert.equal((await db.query('SELECT status FROM inquiries WHERE id=$1', [id])).rows[0].status, 'open', 'close-before-send also reopens');
    }
    await assert.rejects(db.query(`INSERT INTO inquiry_messages(inquiry_id,sender_id,content,id) VALUES(2,'${guest}','rollback',1)`), /duplicate key/);
  } finally { await db.close(); }
});

test('activity uses real timestamps, oldest unanswered customer message, correct sender roles; bounded admin ack preserves customer read state', async () => {
  const db = await fixture();
  try {
    await db.exec(migration);
    await db.exec(`
      INSERT INTO inquiry_messages(inquiry_id,sender_id,content,created_at) VALUES
      (2,'${admin}','reply','2026-10-01T05:00Z'),
      (2,'${guest}','first question','2026-10-01T05:10Z'),
      (2,'${guest}','extra question','2026-10-01T05:40Z');
    `);
    const activity = async id => (await as(db, 'service_role', admin, 'SELECT * FROM get_admin_inquiry_activity(ARRAY[$1]::bigint[])', [id])).rows[0];
    const pending = await activity(2);
    assert.equal(pending.last_sender_role, 'customer'); assert.equal(pending.needs_reply, true);
    assert.equal(pending.reply_waiting_since.toISOString(), new Date('2026-10-01T05:10Z').toISOString());
    assert.equal(pending.last_message_at.toISOString(), new Date('2026-10-01T05:40Z').toISOString());
    assert.equal(pending.last_message_content, 'extra question');
    assert.equal((await activity(1)).last_sender_role, 'host');
    const id = (await db.query('SELECT max(id) AS id FROM inquiry_messages WHERE inquiry_id=2')).rows[0].id;
    await db.exec(`INSERT INTO inquiry_messages(inquiry_id,sender_id,content) VALUES(2,'${guest}','arrived after snapshot')`);
    await as(db, 'service_role', admin, 'SELECT ack_admin_inquiry_messages(2,$1)', [id]);
    assert.equal(Number((await activity(2)).admin_unread_count), 1, 'new arrival stays administratively unread');
    const receipts = (await db.query('SELECT is_read,read_at FROM inquiry_messages WHERE inquiry_id=2')).rows;
    assert.ok(receipts.every(m => !m.is_read && m.read_at === null));
    assert.equal((await activity(2)).needs_reply, true, 'viewing is not replying');
    await db.exec(`INSERT INTO inquiry_messages(inquiry_id,sender_id,content,created_at) VALUES(2,'${whitelist}','official reply',null)`);
    const replied = await activity(2);
    assert.equal(replied.last_sender_role, 'admin'); assert.equal(replied.needs_reply, false); assert.equal(replied.reply_waiting_since, null); assert.equal(replied.last_message_at, null);
    await db.exec(`INSERT INTO inquiry_messages(inquiry_id,sender_id,content,created_at) VALUES(2,'${guest}','unknown first time',null),(2,'${guest}','known later time','2026-10-02T06:42Z')`);
    assert.equal((await activity(2)).reply_waiting_since, null, 'missing first timestamp cannot be replaced with a later one');
  } finally { await db.close(); }
});
