import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import { PGlite } from '@electric-sql/pglite';
import { historyActors, repairedHistoryIds, historicalReinquirySeedSql, captureHistory } from './helpers/adminHistoricalReinquiryFixture.mjs';

const phase1 = readFileSync('supabase/migrations/20261001170718_admin_message_monitoring_phase_1.sql', 'utf8');
const repair = readFileSync('supabase/migrations/20261002015110_admin_message_monitoring_historical_reinquiry.sql', 'utf8');

test('historical repair requires dated latest completion + later final customer, is idempotent and preserves receipts/permissions', async () => {
  const db = new PGlite();
  try {
    await db.exec(`
      CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role BYPASSRLS;
      CREATE SCHEMA auth;
      CREATE TABLE auth.users(id uuid PRIMARY KEY,email text);
      CREATE TABLE users(id uuid PRIMARY KEY,role text);
      CREATE TABLE admin_whitelist(id bigint,email text);
      CREATE TABLE inquiries(id bigint PRIMARY KEY,user_id uuid,host_id uuid,type text,status text,content text,updated_at timestamptz);
      CREATE TABLE inquiry_messages(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,inquiry_id bigint REFERENCES inquiries(id),sender_id uuid,content text,type text DEFAULT 'text',is_read boolean DEFAULT false,read_at timestamptz,created_at timestamptz DEFAULT now());
      GRANT ALL ON inquiries,inquiry_messages TO anon,authenticated,service_role;
      INSERT INTO users VALUES ${Object.entries(historyActors).map(([role,id]) => `('${id}','${role === 'admin' ? 'admin' : 'guest'}')`).join(',')};
      INSERT INTO auth.users VALUES('${historyActors.whitelist}','staff@example.invalid');
      INSERT INTO admin_whitelist VALUES(1,'staff@example.invalid');
    `);
    await db.exec(historicalReinquirySeedSql());
    await db.exec(phase1);
    const before = await captureHistory(db);
    await db.exec(repair);
    const after = await captureHistory(db);
    const changed = after.inquiries.filter(row => row.status !== before.inquiries.find(old => old.id === row.id).status);
    assert.deepEqual(changed.map(row => row.id), repairedHistoryIds);
    assert.ok(changed.every(row => row.status === 'open'));
    assert.equal(changed[0].support_reopened_at.toISOString(), '2026-09-01T00:11:00.000Z', 'use the first real follow-up time, never migration time');
    assert.ok(changed.slice(1).every(row => row.support_reopened_at.toISOString() === '2026-09-01T00:30:00.000Z'));
    assert.deepEqual(after.messages, before.messages, 'customer/admin receipt state and message contents stay identical');
    for (const row of after.inquiries.filter(row => !repairedHistoryIds.includes(row.id))) {
      assert.deepEqual(row, before.inquiries.find(old => old.id === row.id), `insufficient evidence row ${row.id} untouched`);
    }
    const audit = after.audit.filter(row => row.action_type === 'ADMIN_INQUIRY_HISTORICAL_REOPEN');
    assert.equal(audit.length, 3); assert.ok(audit.every(row => row.admin_id === null));
    assert.deepEqual(audit.map(row => Number(row.target_id)), repairedHistoryIds);
    for (const entry of audit) {
      const old = before.audit.find(row => row.id === entry.details.resolved_audit_id);
      assert.equal(new Date(entry.details.resolved_at).toISOString(), old.created_at.toISOString());
      assert.equal(entry.details.before_status, 'resolved'); assert.equal(entry.details.after_status, 'open');
    }
    await db.exec(repair); assert.deepEqual(await captureHistory(db), after, 'second application changes nothing');
    const activity = (await db.query('SELECT * FROM get_admin_inquiry_activity(ARRAY[201,202,213]::bigint[])')).rows;
    assert.ok(activity.every(row => row.needs_reply && row.last_sender_role === 'customer'));
    assert.equal((await db.query("SELECT has_any_column_privilege('authenticated','inquiry_messages','UPDATE') AS allowed")).rows[0].allowed, false);
  } finally { await db.close(); }
});
