import assert from 'node:assert/strict';
import {test,after} from 'node:test';
import {mkdtemp,rm,mkdir,readFile} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import path from 'node:path';
import {build} from 'esbuild';
import {COMMUNITY_BUCKET,COMMUNITY_BASE_URL,communityKey,communityWriteAuthority} from '../../app/utils/communityMediaContract.mjs';
import {communityLocalDecoder} from '../../scripts/cloudflare/community-local-decoder.mjs';
import {createRequire} from 'node:module';
const sharp=createRequire(import.meta.resolve('miniflare'))('sharp');
await mkdir('.tmp',{recursive:true});const dir=await mkdtemp(path.resolve('.tmp/community-unit-'));
await build({entryPoints:['app/utils/communityMedia.ts','app/utils/communityUploadHandler.ts','app/utils/communityImageSetHandler.ts','app/utils/communityImageUpload.ts'],bundle:true,platform:'node',format:'esm',outdir:dir});
const core=await import(pathToFileURL(dir+'/communityMedia.js')),{createCommunityUploadHandlers}=await import(pathToFileURL(dir+'/communityUploadHandler.js')),{createCommunityImageSetHandler}=await import(pathToFileURL(dir+'/communityImageSetHandler.js')),{uploadCommunityImage}=await import(pathToFileURL(dir+'/communityImageUpload.js'));after(()=>rm(dir,{recursive:true,force:true}));
const owner='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222';
const bytes=await sharp({create:{width:2,height:2,channels:3,background:'red'}}).jpeg().toBuffer();
function fixture({failure,auth=true,profileOwner=owner,flag='true'}={}){
 let asset;const events=[],objects=new Map();const registry={async rpc(name,a){events.push(name);if(name==='begin_community_media_asset')asset={id:a.p_id,owner_id:a.p_owner_id,business_scope:'community',parent_type:'community_owner',parent_id:a.p_owner_id,provider:'r2',bucket:COMMUNITY_BUCKET,object_key:a.p_key,public_url:a.p_url,expected_sha256:a.p_sha256,expected_size:a.p_size,mime:a.p_mime,state:'pending'};else if(name==='mark_community_media_uploaded')asset.uploaded_at='fixture';else if(name==='verify_community_media_asset')asset.verified_at='fixture';return {data:failure==='owner'?{...asset,owner_id:other}:asset,error:failure===name?{}:null}}};
 const binding={async head(k){if(failure==='head')throw Error('private secret');return objects.get(k)??null},async get(k){events.push('GET');return objects.get(k)},async put(k,b,o){events.push('PUT');assert.deepEqual(o.onlyIf,{etagDoesNotMatch:'*'});if(failure==='put')throw Error('private secret');assert(!objects.has(k));objects.set(k,{size:b.length,httpMetadata:o.httpMetadata,customMetadata:o.customMetadata,arrayBuffer:async()=>failure==='bytes'?new Uint8Array([1]).buffer:b.slice().buffer});return objects.get(k)}};
 const client={auth:{getUser:async()=>({data:{user:auth?{id:owner}:null},error:null})},from(){const q={select(){return q},eq(){return q},single:async()=>({data:{id:profileOwner},error:null})};return q},storage:{from(){events.push('Supabase');throw Error('fallback')}}};
 const env={CLOUDFLARE_DEPLOYMENT_ENV:'production',COMMUNITY_R2_SOURCE_ENABLED:flag,PUBLIC_COMMUNITY_SOURCE_R2:binding,IMAGES:communityLocalDecoder};
 return {events,objects,registry,binding,env,client,asset:()=>asset,handler:createCommunityUploadHandlers({createClient:async()=>client,createAdminClient:()=>registry,loadRuntime:()=>env}),input:{registry,binding,decoder:communityLocalDecoder,actorId:owner,ownerId:owner,bytes,contentType:'image/jpeg'}};
}
function request({origin='https://app.test',extra,length,payload=bytes}={}){const form=new FormData();form.set('file',new File([payload],'fixture.jpg',{type:'image/jpeg'}));if(extra)form.set('ownerId',extra);return new Request('https://app.test/api/community/images',{method:'POST',headers:{origin,...(length?{'content-length':length}:{})},body:form});}
test('COMMUNITY_SOURCE_BYTE_VERIFIED: pending, immutable identity, upload then full GET SHA before verified',async()=>{const f=fixture(),a=await core.prepareCommunityAsset(f.input);assert.equal(a.state,'pending');assert(a.uploaded_at&&a.verified_at);assert(!a.object_key.includes(owner));assert.equal(a.object_key,communityKey(owner,a.id));assert.deepEqual(f.events,['begin_community_media_asset','PUT','mark_community_media_uploaded','GET','verify_community_media_asset']);const again=await core.prepareCommunityAsset({...f.input,assetId:a.id});assert.equal(again.id,a.id);assert.equal(f.events.filter(x=>x==='PUT').length,1);});
test('COMMUNITY_R2_FAIL_CLOSED: provider/registry/SHA/owner error never verifies or uses Supabase',async()=>{for(const failure of ['put','head','bytes','owner','verify_community_media_asset']){const f=fixture({failure});const r=await f.handler.POST(request());assert(r.status>=400);assert(!f.events.includes('Supabase'));assert(!JSON.stringify(await r.json()).includes('secret'));}assert.throws(()=>communityWriteAuthority({COMMUNITY_R2_SOURCE_ENABLED:'true'}));assert.throws(()=>communityWriteAuthority({COMMUNITY_R2_SOURCE_ENABLED:'typo'}));assert.equal(communityWriteAuthority({AVATAR_R2_SOURCE_ENABLED:'true'}),'supabase');});
test('COMMUNITY_SERVER_WRITE_AUTHORITY_READY: actor, origin, metadata and actual stream bounds before registration',async()=>{for(const [setup,arg,status] of [[{auth:false},{},401],[{profileOwner:other},{},403],[{}, {origin:'https://foreign'},403],[{}, {extra:other},400],[{}, {length:'1'},413]]){const f=fixture(setup);assert.equal((await f.handler.POST(request(arg))).status,status);assert.equal(f.events.length,0);}const f=fixture();await assert.rejects(core.prepareCommunityAsset({...f.input,actorId:other}));});
test('COMMUNITY_BROWSER_DIRECT_SUPABASE_WRITE_DISABLED_WHEN_R2_ACTIVE: actual browser helper no failure fallback',async()=>{let legacyCalls=0;const legacy=async()=>{legacyCalls++;return {publicUrl:'legacy'}};const file=new File([bytes],'a.jpg',{type:'image/jpeg'});for(const response of [Response.json({error:'failed'},{status:503}),Response.json({authority:'supabase'}),Response.json({authority:'r2',assetId:'wrong',publicUrl:'https://foreign'})])await assert.rejects(uploadCommunityImage(file,'r2',legacy,async()=>response));assert.equal(legacyCalls,0);const id=crypto.randomUUID(),url=COMMUNITY_BASE_URL+'/'+communityKey(owner,id);assert.deepEqual(await uploadCommunityImage(file,'r2',legacy,async()=>Response.json({authority:'r2',assetId:id,publicUrl:url})),{assetId:id,publicUrl:url});assert.equal(legacyCalls,0);await uploadCommunityImage(file,'supabase',legacy);assert.equal(legacyCalls,1);const editor=await readFile('app/community/write/PostEditor.tsx','utf8');assert.match(editor,/uploadCommunityImage\(compressed, selection.authority/);});
test('media-only image set endpoint refuses nonowned/stale RPC and unrelated fields',async()=>{const f=fixture();let args;const h=createCommunityImageSetHandler({createClient:async()=>f.client,createAdminClient:()=>({rpc:async(name,a)=>{assert.equal(name,'commit_community_post_images');args=a;return {data:null,error:{}}}})});const id=crypto.randomUUID(),url=COMMUNITY_BASE_URL+'/'+communityKey(owner,crypto.randomUUID());const body={post_id:id,expected_revision:0,expected_images:[],images:[url]};const req=b=>new Request('https://app.test/api/community/posts/images',{method:'PATCH',headers:{origin:'https://app.test'},body:JSON.stringify(b)});assert.equal((await h(req(body))).status,409);assert.equal(args.p_actor_id,owner);assert.equal((await h(req({...body,content:'outside boundary'}))).status,400);assert.equal((await h(req({...body,images:['https://foreign']}))).status,400);});
test('Community reader host is additive; legacy and OAuth/Avatar/Host readers remain',async()=>{const config=await readFile('next.config.ts','utf8');for(const host of ['community-media.locally-travel.com','avatars-media.locally-travel.com','host-profile-media.locally-travel.com','*.supabase.co','lh3.googleusercontent.com'])assert(config.includes(host));const route=await readFile('app/api/community/posts/route.ts','utf8');assert.match(route,/communityWriteAuthority\(loadCommunityRuntime\(\), process.env.COMMUNITY_R2_SOURCE_ENABLED\)/);assert.match(route,/communityKey\(user.id/);});
