import assert from 'node:assert/strict';
import {test,after} from 'node:test';
import {readFile,mkdtemp,rm,mkdir} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import path from 'node:path';
import {build} from 'esbuild';
import {HOST_PROFILE_BUCKET,HOST_PROFILE_BASE_URL,hostProfileKey,hostProfileWriteAuthority} from '../../app/utils/hostProfileMediaContract.mjs';
await mkdir('.tmp',{recursive:true});const dir=await mkdtemp(path.resolve('.tmp/host-profile-tests-'));
await build({entryPoints:['app/utils/hostProfileMedia.ts','app/utils/hostProfileUploadHandler.ts'],bundle:true,platform:'node',format:'esm',outdir:dir});
const core=await import(pathToFileURL(dir+'/hostProfileMedia.js')),{createHostProfileUploadHandler}=await import(pathToFileURL(dir+'/hostProfileUploadHandler.js'));after(()=>rm(dir,{recursive:true,force:true}));
const owner='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222',bytes=new Uint8Array([255,216,255,1,2]);
function fixture({failure,flag='true',auth=true,profileOwner=owner}={}){
 let asset;const objects=new Map(),events=[];const registry={async rpc(name,a){events.push(name);if(name==='begin_host_profile_media_asset')asset={id:a.p_id,owner_id:a.p_owner_id,business_scope:'host_profile',parent_type:'host_profile_owner',parent_id:a.p_owner_id,provider:'r2',bucket:HOST_PROFILE_BUCKET,object_key:a.p_key,public_url:a.p_url,expected_sha256:a.p_sha256,expected_size:a.p_size,mime:a.p_mime,state:'pending'};else if(name==='verify_host_profile_media_asset')Object.assign(asset,{uploaded_at:'fixture',verified_at:'fixture'});return {data:failure==='owner'?{...asset,owner_id:other}:asset,error:failure===name?{}:null};}};
 const binding={async head(k){if(failure==='head')throw Error('private secret detail');return objects.get(k)??null;},async put(k,b,o){events.push('PUT');assert.deepEqual(o.onlyIf,{etagDoesNotMatch:'*'});if(failure==='put')throw Error('private secret detail');objects.set(k,{size:b.length,httpMetadata:o.httpMetadata,customMetadata:o.customMetadata,arrayBuffer:async()=>failure==='bytes'?new Uint8Array([9,9]).buffer:b.slice().buffer});return failure==='concurrent'?null:objects.get(k);},async get(k){events.push('GET');return objects.get(k);}};
 const client={auth:{getUser:async()=>({data:{user:auth?{id:owner}:null},error:null})},from(){const q={select(){return q;},eq(){return q;},single:async()=>({data:{id:profileOwner},error:null})};return q;},storage:{from(bucket){assert.equal(bucket,'images');return {upload:async(k)=>{events.push('SupabasePUT');assert(k.startsWith('profile/'+owner+'_'));return {error:null};},getPublicUrl:k=>({data:{publicUrl:'https://fixture/'+k}})};}}};
 const env={CLOUDFLARE_DEPLOYMENT_ENV:'production',HOST_PROFILE_R2_SOURCE_ENABLED:flag,PUBLIC_HOST_PROFILE_SOURCE_R2:binding};const handler=createHostProfileUploadHandler({createClient:async()=>client,createAdminClient:()=>registry,loadRuntime:()=>env});return {registry,binding,env,handler,events,asset:()=>asset,input:{registry,binding,actorId:owner,ownerId:owner,bytes,contentType:'image/jpeg'}};
}
function request({origin='https://app.test',extra,payload=bytes,mime='image/jpeg'}={}){const form=new FormData();form.set('file',new File([payload],'fixture.jpg',{type:mime}));if(extra)form.set('ownerId',extra);return new Request('https://app.test/api/host/profile-photo',{method:'POST',headers:{origin,'content-length':String(payload.length+1024)},body:form});}
test('HOST_AVATAR_AUTHORITY_SEPARATED: exact dedicated immutable bucket, opaque namespace, independent flag',()=>{const k=hostProfileKey(owner,crypto.randomUUID());assert(!k.includes(owner));assert.match(k,/^host-profiles\/v1\/[a-f0-9]{64}\/[^/]+\/profile$/);assert.equal(hostProfileWriteAuthority(fixture().env),'r2');assert.equal(hostProfileWriteAuthority({AVATAR_R2_SOURCE_ENABLED:'true',PUBLIC_AVATAR_R2:{}}),'supabase');for(const e of [{HOST_PROFILE_R2_SOURCE_ENABLED:'true',PUBLIC_AVATAR_R2:{}},{HOST_PROFILE_R2_SOURCE_ENABLED:'true',PUBLIC_EXPERIENCE_MEDIA_SOURCE_R2:{}},{HOST_PROFILE_R2_SOURCE_ENABLED:'typo'}, {...fixture().env,CLOUDFLARE_DEPLOYMENT_ENV:'canary'}])assert.throws(()=>hostProfileWriteAuthority(e));});
test('Host format behavior preserves compression fallback; independent size and raster magic validation',()=>{for(const mime of ['image/svg+xml','image/bmp'])assert.equal(core.validateHostProfileImage(new TextEncoder().encode('fixture'),mime),mime);for(const [b,m] of [[bytes,'image/png'],[bytes,'image/heic'],[bytes,'image/heif'],[new Uint8Array(),'image/jpeg'],[new Uint8Array(10485761),'image/jpeg']])assert.throws(()=>core.validateHostProfileImage(b,m));});
test('prepare verifies bytes yet leaves pending until a business reference commits',async()=>{const f=fixture(),a=await core.prepareHostProfileAsset(f.input);assert.equal(a.state,'pending');assert(a.verified_at&&a.uploaded_at);assert.deepEqual(f.events,['begin_host_profile_media_asset','PUT','GET','verify_host_profile_media_asset']);assert.equal(a.public_url,HOST_PROFILE_BASE_URL+'/'+a.object_key);});
test('provider/registry/owner/SHA failures never commit, overwrite, delete or select Avatar authority',async()=>{for(const failure of ['head','put','owner','bytes','verify_host_profile_media_asset']){const f=fixture({failure});await assert.rejects(core.prepareHostProfileAsset(f.input));assert.equal(f.asset().state,'pending');assert(!f.events.includes('SupabasePUT'));assert(!('delete' in f.binding));}const f=fixture();await assert.rejects(core.prepareHostProfileAsset({...f.input,actorId:other}));assert.equal(f.events.length,0);});
test('same-origin, current user and owned row; browser cannot choose object identity',async()=>{for(const [setup,arg,status] of [[{auth:false},{},401],[{profileOwner:other},{},403],[{}, {origin:'https://evil.test'},403],[{}, {extra:other},400],[{}, {mime:'image/png'},400]]){const f=fixture(setup);assert.equal((await f.handler(request(arg))).status,status);assert.equal(f.events.length,0);}});
test('server controlled compatibility before gate; R2 enabled failure is fail-closed',async()=>{const old=fixture({flag:'false'});assert.equal((await old.handler(request())).status,200);assert.deepEqual(old.events,['SupabasePUT']);const next=fixture();const response=await next.handler(request());assert.equal(response.status,200);assert.equal((await response.json()).authority,'r2');assert.equal(next.asset().state,'pending');for(const failure of ['head','put','bytes']){const f=fixture({failure});const r=await f.handler(request());assert.equal(r.status,503);assert(!f.events.includes('SupabasePUT'));assert(!JSON.stringify(await r.json()).includes('secret'));}});
test('HOST_BROWSER_DIRECT_SUPABASE_WRITE_DISABLED: both Host editors use dedicated endpoint and media CAS',async()=>{const editor=await readFile('app/host/dashboard/components/ProfileEditor.tsx','utf8');assert.match(editor,/uploadHostProfilePhoto\(compressedFile\)/);assert.doesNotMatch(editor,/storage\.from|uploadProfileAvatar/);assert.match(editor,/avatarUrl: photoUploaded \? avatarUrl : profile\?\.host_profile_photo \?\? null/);const registration=await readFile('app/host/register/page.tsx','utf8');assert.match(registration,/uploadHostProfilePhoto\(compressedProfile\)/);assert.doesNotMatch(registration,/`profile\/|uploadProfileAvatar/);for(const file of ['app/api/host/profile/route.ts','app/api/host/register/submit/route.ts']){const s=await readFile(file,'utf8');assert.match(s,/expectedProfilePhoto/);assert.match(s,/(?:applicationUpdate|update)\.(is|eq)\('profile_photo'/);}});
test('Auth preference writer sends only its field; Chat/display and token refresh continue reading current authority',async()=>{const language=await readFile('app/context/LanguageContext.tsx','utf8');const block=language.slice(language.indexOf('void supabase.auth.updateUser'));assert.doesNotMatch(block.slice(0,200),/\.\.\.user\.user_metadata/);assert.match(block.slice(0,200),/preferred_locale: lang/);const chat=await readFile('app/hooks/useChat.ts','utf8');assert.match(chat,/authUser\?\.user_metadata\?\.avatar_url/);const auth=await readFile('app/context/AuthContext.tsx','utf8');assert.match(auth,/avatar_url: profile\?\.avatar_url \|\| authUser\.user_metadata.avatar_url/);assert.match(auth,/onAuthStateChange/);});

test('Host SVG source preserves existing attachment safety while image embedding remains compatible',async()=>{const f=fixture(),a=await core.prepareHostProfileAsset({...f.input,bytes:new TextEncoder().encode('<svg xmlns="http://www.w3.org/2000/svg"/>'),contentType:'image/svg+xml'});assert.equal((await f.binding.head(a.object_key)).httpMetadata.contentDisposition,'attachment');});
